### ISSUE TITLE
Do not run under ubuntu 18.04

### ISSUE THREAD

**Issue by mariovazquezpena** [PinguinoIDE/pinguino-ide#102]
Traceback (most recent call last):
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/core.py", line 1067, in ide_open_file_from_path
    editor.text_edit.setPlainText(content)
AttributeError: 'NoneType' object has no attribute 'text_edit'

os.uname: ('Linux', 'mario-ThinkPad-T540p', '4.18.0-15-generic', '#16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019', 'x86_64')
os.name: posix
os.environ: {'PINGUINO_USER_PATH': '/home/mario/Pinguino/v12', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.41-beta.2', 'QT4_IM_MODULE': 'xim', 'GJS_DEBUG_OUTPUT': 'stderr', 'PINGUINO_DEFAULT_FILES': '/home/mario/Pinguino/v12/local', 'PINGUINO_NAME': 'Pinguino IDE', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'XDG_SESSION_TYPE': 'x11', 'PINGUINO_MODE': 'NORMAL', 'QT_IM_MODULE': 'xim', 'LOGNAME': 'mario', 'XDG_SEAT': 'seat0', 'PINGUINO_PROJECT': '', 'HOME': '/home/mario', 'XDG_VTNR': '2', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'PINGUINO_8_LIBS_PATH': '/opt/pinguino/v12/p8', 'DISPLAY': ':0', 'SSH_AGENT_PID': '1233', 'LANG': 'es_MX.UTF-8', 'SHELL': '/bin/bash', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'LANGUAGE': 'es_MX:es', 'SESSION_MANAGER': 'local/mario-ThinkPad-T540p:@/tmp/.ICE-unix/1156,unix/mario-ThinkPad-T540p:/tmp/.ICE-unix/1156', 'SHLVL': '0', 'CLUTTER_IM_MODULE': 'xim', 'PINGUINO_OS_ARCH': '64bit', 'PINGUINO_OS_NAME': 'linux', 'TEXTDOMAIN': 'im-config', 'QT_ACCESSIBILITY': '1', 'WINDOWPATH': '2', 'IM_CONFIG_PHASE': '2', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '17658', 'PINGUINO_VERSION': '12.0.41-beta.2', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'USERNAME': 'mario', 'XDG_SESSION_DESKTOP': 'ubuntu', 'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/pinguino12.desktop', 'PINGUINO_32_LIBS_PATH': '/opt/pinguino/v12/p32', 'XDG_RUNTIME_DIR': '/run/user/1000', 'PINGUINO_LIBS_PATH': '/opt/pinguino/v12', 'PINGUINO_LIB': '/opt/pinguino/v12/pinguino', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'GDMSESSION': 'ubuntu', 'XMODIFIERS': '@im=ibus', 'TEXTDOMAINDIR': '/usr/share/locale/', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'PINGUINO_PYTHON': '2', 'XDG_SESSION_ID': '2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'GTK_IM_MODULE': 'ibus', 'DESKTOP_SESSION': 'ubuntu', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'GTK_MODULES': 'gail:atk-bridge', 'PINGUINO_USERLIBS_PATH': '/opt/pinguino/v12/pinguinolibs', 'PINGUINO_BOARD_ARCH': '8', 'PINGUINO_INSTALL_PATH': '/opt/pinguino/v12', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'PWD': '/home/mario', 'XDG_MENU_PREFIX': 'gnome-', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'PINGUINO_CAN_COMPILE': 'True', 'USER': 'mario'}

**Comment by MefhigosetH** [comment]
Duplicate #122
