### ISSUE TITLE
Pinguino

### ISSUE THREAD

**Issue by Viddar6** [PinguinoIDE/pinguino-ide#104]
Traceback (most recent call last):
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/ide.py", line 132, in __init__
    self.PinguinoAutoCompleter = PinguinoAutoCompleter()
  File "/opt/pinguino/v12/pinguino/qtgui/ide/custom_widgets/code_editor/autocompleter.py", line 59, in __init__
    with open(os.path.join(os.getenv("PINGUINO_USER_PATH"), "reserved.pickle"), "rb") as file_reserved:
IOError: [Errno 2] No existe el archivo o el directorio: '/home/vidar-berserker/Pinguino/v12/reserved.pickle'

os.uname: ('Linux', 'vidarberserker-Lenovo-ideapad-110-14ISK', '4.4.0-142-generic', '#168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019', 'x86_64')
os.name: posix
os.environ: {'PINGUINO_LIB': '/opt/pinguino/v12/pinguino', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'PINGUINO_USER_PATH': '/home/vidar-berserker/Pinguino/v12', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/vidar-berserker', 'QT4_IM_MODULE': 'xim', 'UPSTART_EVENTS': 'xsession started', 'PINGUINO_NAME': 'Pinguino IDE', 'XDG_CURRENT_DESKTOP': 'Unity', 'UNITY_HAS_3D_SUPPORT': 'true', 'XDG_SESSION_TYPE': 'x11', 'PINGUINO_MODE': 'NORMAL', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'vidar-berserker', 'USER': 'vidar-berserker', 'PINGUINO_PROJECT': '', 'HOME': '/home/vidar-berserker', 'XDG_VTNR': '7', 'PATH': '/home/vidar-berserker/bin:/home/vidar-berserker/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'PINGUINO_8_LIBS_PATH': '/opt/pinguino/v12/p8', 'DISPLAY': ':0', 'GNOME_KEYRING_CONTROL': '', 'PINGUINO_32_LIBS_PATH': '/opt/pinguino/v12/p32', 'LANG': 'es_MX.UTF-8', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XAUTHORITY': '/home/vidar-berserker/.Xauthority', 'LANGUAGE': 'es_MX:es', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'SHLVL': '0', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'CLUTTER_IM_MODULE': 'xim', 'UNITY_DEFAULT_PROFILE': 'unity', 'PINGUINO_OS_ARCH': '64bit', 'PINGUINO_OS_NAME': 'linux', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'QT_ACCESSIBILITY': '1', 'SESSION': 'ubuntu', 'UPSTART_INSTANCE': '', 'SESSIONTYPE': 'gnome-session', 'XMODIFIERS': '@im=ibus', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '2118', 'PINGUINO_VERSION': '12.0.41-beta.2', 'GPG_AGENT_INFO': '/home/vidar-berserker/.gnupg/S.gpg-agent:0:1', 'GTK2_MODULES': 'overlay-scrollbar', 'XDG_SESSION_DESKTOP': 'ubuntu', 'COMPIZ_BIN_PATH': '/usr/bin/', 'XDG_RUNTIME_DIR': '/run/user/1000', 'PINGUINO_LIBS_PATH': '/opt/pinguino/v12', 'INSTANCE': '', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/pinguino12.desktop', 'GDMSESSION': 'ubuntu', 'IM_CONFIG_PHASE': '1', 'UPSTART_JOB': 'unity7', 'PINGUINO_PYTHON': '2', 'GNOME_KEYRING_PID': '', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_SESSION_ID': 'c1', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-brh9pq6aYz', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'GTK_IM_MODULE': 'ibus', 'DESKTOP_SESSION': 'ubuntu', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/1005', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.41-beta.2', 'PINGUINO_USERLIBS_PATH': '/opt/pinguino/v12/pinguinolibs', 'PINGUINO_DEFAULT_FILES': '/home/vidar-berserker/Pinguino/v12/local', 'SESSION_MANAGER': 'local/vidarberserker-Lenovo-ideapad-110-14ISK:@/tmp/.ICE-unix/1317,unix/vidarberserker-Lenovo-ideapad-110-14ISK:/tmp/.ICE-unix/1317', 'GDM_LANG': 'es', 'PINGUINO_INSTALL_PATH': '/opt/pinguino/v12', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop', 'PWD': '/home/vidar-berserker', 'JOB': 'unity-settings-daemon', 'XDG_MENU_PREFIX': 'gnome-', 'PINGUINO_BOARD_ARCH': '8', 'PINGUINO_CAN_COMPILE': 'True', 'XDG_SEAT': 'seat0'}

**Comment by MefhigosetH** [comment]
Duplicate #118
