### ISSUE TITLE
FileNotFoundError reserved.pickle

### ISSUE THREAD

**Issue by orlandomax** [PinguinoIDE/pinguino-ide#109]
Traceback (most recent call last):
  File "/opt/pinguino/v13/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v13/pinguino/qtgui/ide/ide.py", line 132, in __init__
    self.PinguinoAutoCompleter = PinguinoAutoCompleter()
  File "/opt/pinguino/v13/pinguino/qtgui/ide/custom_widgets/code_editor/autocompleter.py", line 59, in __init__
    with open(os.path.join(os.getenv("PINGUINO_USER_PATH"), "reserved.pickle"), "rb") as file_reserved:
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/home/orlando/Pinguino/v13/reserved.pickle'

os.uname: posix.uname_result(sysname='Linux', nodename='orlando-desktop', release='4.4.0-145-generic', version='#171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019', machine='x86_64')
os.name: posix
os.environ: environ({'JOB': 'dbus', 'PINGUINO_VERSION': '13.0.0', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'PINGUINO_MODE': 'NORMAL', 'XDG_VTNR': '7', 'GNOME_KEYRING_CONTROL': '', 'GTK2_MODULES': 'overlay-scrollbar', 'XDG_CURRENT_DESKTOP': 'Unity', 'GDM_LANG': 'es_ES', 'TERM': 'xterm-256color', 'LC_NAME': 'es_VE.UTF-8', 'SESSION_MANAGER': 'local/orlando-desktop:@/tmp/.ICE-unix/3049,unix/orlando-desktop:/tmp/.ICE-unix/3049', 'PAPERSIZE': 'letter', 'INSTANCE': '', 'SESSION': 'ubuntu', 'LC_NUMERIC': 'es_VE.UTF-8', 'XDG_SESSION_TYPE': 'x11', 'PINGUINO_NAME': 'Pinguino IDE', 'LC_TELEPHONE': 'es_VE.UTF-8', 'GNOME_KEYRING_PID': '', 'QT_IM_MODULE': 'ibus', 'PINGUINO_MAJOR': '13', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'GTK_IM_MODULE': 'ibus', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'PATH': '/home/orlando/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/microchip/xc8/v1.41/bin:/opt/microchip/xc8/v1.44/bin:/opt/microchip/xc8/v1.45/bin:/home/orlando/.local/bin:/opt/microchip/xc8/v1.41/bin:/opt/microchip/xc8/v1.44/bin:/opt/microchip/xc8/v1.45/bin', 'PINGUINO_OS_ARCH': '64bit', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/2766', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-211uCCwk4F', 'PINGUINO_32_LIBS_PATH': '/home/orlando/Dvpt/pinguino/git-local/pinguino-libraries/p32', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop', 'XMODIFIERS': '@im=ibus', 'PINGUINO_PATCH': '0', 'PINGUINO_PROJECT': '', 'PINGUINO_LIB': '/opt/pinguino/v13/pinguino', 'PINGUINO_MINOR': '0', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'PINGUINO_FULLNAME': 'Pinguino IDE 13.0.0', 'PINGUINO_INSTALL_PATH': '/opt/pinguino/v13', 'IM_CONFIG_PHASE': '1', 'QT_ACCESSIBILITY': '1', 'XAUTHORITY': '/home/orlando/.Xauthority', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/orlando', 'WINDOWID': '54526580', 'XDG_SESSION_ID': 'c2', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'LC_PAPER': 'es_VE.UTF-8', 'PINGUINO_PYTHON': '3', 'VTE_VERSION': '4205', 'LC_IDENTIFICATION': 'es_VE.UTF-8', 'XDG_SESSION_DESKTOP': 'ubuntu', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'PINGUINO_8_LIBS_PATH': '/home/orlando/Dvpt/pinguino/git-local/pinguino-libraries/p8', 'LC_MONETARY': 'es_VE.UTF-8', 'PWD': '/home/orlando/pythonprueba', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'LC_TIME': 'es_VE.UTF-8', 'LC_MEASUREMENT': 'es_VE.UTF-8', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'DISPLAY': ':0', 'DESKTOP_SESSION': 'ubuntu', 'GDMSESSION': 'ubuntu', 'XDG_MENU_PREFIX': 'gnome-', 'CLUTTER_IM_MODULE': 'xim', 'LOGNAME': 'orlando', 'PINGUINO_BOARD_ARCH': '8', 'SESSIONTYPE': 'gnome-session', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', '_': '/usr/bin/python3', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'XDG_RUNTIME_DIR': '/run/user/1000', 'SHLVL': '1', 'PINGUINO_LIBS_PATH': '/home/orlando/Dvpt/pinguino/git-local/pinguino-libraries', 'LANG': 'es_ES.UTF-8', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'LC_ADDRESS': 'es_VE.UTF-8', 'HOME': '/home/orlando', 'PINGUINO_DEFAULT_FILES': '/home/orlando/Pinguino/v13/local', 'PINGUINO_OS_NAME': 'linux', 'PINGUINO_USER_PATH': '/home/orlando/Pinguino/v13', 'XDG_SEAT': 'seat0', 'GPG_AGENT_INFO': '/home/orlando/.gnupg/S.gpg-agent:0:1', 'PINGUINO_CAN_COMPILE': 'True', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'QT4_IM_MODULE': 'xim', 'LANGUAGE': 'es_ES:en', 'USER': 'orlando', 'PINGUINO_USERLIBS_PATH': '/home/orlando/Pinguino/v13/user/pinguinolibs'})

**Comment by AlfredBroda** [comment]
Issue #112 seems very similar.

**Comment by luvhines** [comment]
It says that the file "reserved.pickle" does not exist in the v13 directory, you can download that file right here in git, copy it in the directory, that fixes the problem
