### ISSUE TITLE
bootloaders

### ISSUE THREAD

**Issue by isamh** [PinguinoIDE/pinguino-ide#110]
Traceback (most recent call last):
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/core.py", line 1067, in ide_open_file_from_path
    editor.text_edit.setPlainText(content)
AttributeError: 'NoneType' object has no attribute 'text_edit'

os.uname: ('Linux', 'Lenovo-G50-30', '4.8.0-53-generic', '#56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017', 'x86_64')
os.name: posix
os.environ: {'QT_QPA_PLATFORMTHEME': 'qgnomeplatform', 'PINGUINO_USER_PATH': '/home/isaias/Pinguino/v12', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/isaias', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'GJS_DEBUG_OUTPUT': 'stderr', 'PINGUINO_DEFAULT_FILES': '/home/isaias/Pinguino/v12/local', 'PINGUINO_NAME': 'Pinguino IDE', 'XDG_CURRENT_DESKTOP': 'X-Cinnamon', 'XDG_SESSION_TYPE': 'x11', 'PINGUINO_BOARD_ARCH': '8', 'LOGNAME': 'isaias', 'XDG_SEAT': 'seat0', 'HOME': '/home/isaias', 'XDG_VTNR': '7', 'PATH': '/home/isaias/bin:/home/isaias/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/microchip/xc8/v2.05/bin', 'PINGUINO_8_LIBS_PATH': '/opt/pinguino/v12/p8', 'DISPLAY': ':0', 'SSH_AGENT_PID': '1564', 'LANG': 'es_MX.UTF-8', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XAUTHORITY': '/home/isaias/.Xauthority', 'LANGUAGE': 'es_MX:es', 'SESSION_MANAGER': 'local/Lenovo-G50-30:@/tmp/.ICE-unix/1405,unix/Lenovo-G50-30:/tmp/.ICE-unix/1405', 'SHLVL': '0', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'MANDATORY_PATH': '/usr/share/gconf/cinnamon.mandatory.path', 'PINGUINO_OS_ARCH': '64bit', 'PINGUINO_OS_NAME': 'linux', 'PINGUINO_PROJECT': '', 'QT_ACCESSIBILITY': '1', 'PINGUINO_PYTHON': '2', 'GTK_OVERLAY_SCROLLING': '1', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '4408', 'PINGUINO_VERSION': '12.0.41-beta.2', 'PINGUINO_32_LIBS_PATH': '/opt/pinguino/v12/p32', 'XDG_SESSION_DESKTOP': 'cinnamon', 'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/pinguino12.desktop', 'XDG_RUNTIME_DIR': '/run/user/1000', 'PINGUINO_LIBS_PATH': '/opt/pinguino/v12', 'PINGUINO_LIB': '/opt/pinguino/v12/pinguino', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'CINNAMON_VERSION': '3.6.7', 'GDMSESSION': 'cinnamon', 'PINGUINO_MODE': 'NORMAL', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_SESSION_ID': 'c2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-9aiWuGQaua,guid=9743a45680fa635123c60d095cd1b264', 'QT_STYLE_OVERRIDE': 'gtk', 'DESKTOP_SESSION': 'cinnamon', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-cinnamon:/etc/xdg', 'DEFAULTS_PATH': '/usr/share/gconf/cinnamon.default.path', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.41-beta.2', 'PINGUINO_USERLIBS_PATH': '/opt/pinguino/v12/pinguinolibs', 'GDM_LANG': 'es_MX', 'PINGUINO_INSTALL_PATH': '/opt/pinguino/v12', 'XDG_DATA_DIRS': '/usr/share/cinnamon:/usr/share/gnome:/usr/local/share/:/usr/share/', 'PWD': '/home/isaias', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'PINGUINO_CAN_COMPILE': 'True', 'USER': 'isaias'}

**Comment by MefhigosetH** [comment]
Duplicate #122
