### ISSUE TITLE
armhf ubuntu16.04 Linux4.4.49

### ISSUE THREAD

**Issue by PVlado** [PinguinoIDE/pinguino-ide#111]
Traceback (most recent call last):
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 161, in wrapped
    if saved: fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 174, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/core.py", line 786, in pinguino_compile
    compile_code()
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/core.py", line 765, in <lambda>
    compile_code = lambda :self.pinguinoAPI.compile_file([filename])
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/pinguino.py", line 85, in compile_file
    data = self.verify(file_path)
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/pinguino_tools.py", line 253, in verify
    retour, error_compile = self.compile()
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/pinguino_tools.py", line 915, in compile
    stderr=STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

os.uname: ('Linux', 'FriendlyELEC', '4.4.49-s5p6818', '#1 SMP PREEMPT Thu Dec 13 16:32:44 CST 2018', 'armv7l')
os.name: posix
os.environ: {'LC_NUMERIC': 'en', 'PINGUINO_LIB': '/opt/pinguino/v12/pinguino', 'QT_QPA_PLATFORMTHEME': 'lxqt', '_LXSESSION_PID': '1141', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/pi', 'QT4_IM_MODULE': '', 'QT_PLATFORM_PLUGIN': 'lxqt', 'LC_MEASUREMENT': 'en', 'UPSTART_EVENTS': 'started xsession', 'PINGUINO_NAME': 'Pinguino IDE', 'XDG_CURRENT_DESKTOP': 'LXDE', 'XDG_SESSION_TYPE': 'x11', 'PINGUINO_MODE': 'NORMAL', 'QT_IM_MODULE': '', 'LOGNAME': 'pi', 'XDG_SEAT': 'seat0', 'PINGUINO_PROJECT': '', 'HOME': '/home/pi', 'XDG_VTNR': '7', 'GNOME_KEYRING_CONTROL': '', 'PINGUINO_8_LIBS_PATH': '/opt/pinguino/v12/p8', 'DISPLAY': ':0.0', 'PINGUINO_USER_PATH': '/home/pi/Pinguino/v12', 'XDG_SESSION_DESKTOP': 'Lubuntu', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XAUTHORITY': '/home/pi/.Xauthority', 'LANGUAGE': 'en\nen', 'INSTANCE': '', 'LC_MONETARY': 'en', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'MANDATORY_PATH': '/usr/share/gconf/Lubuntu.mandatory.path', 'CLUTTER_IM_MODULE': '', 'PINGUINO_OS_ARCH': '32bit', 'PINGUINO_OS_NAME': 'linux', 'UPSTART_INSTANCE': '', 'QT_ACCESSIBILITY': '1', 'SESSION': 'Lubuntu', 'PINGUINO_DEFAULT_FILES': '/home/pi/Pinguino/v12/local', 'SESSIONTYPE': 'lxsession', 'IM_CONFIG_PHASE': '1', 'PINGUINO_VERSION': '12.0.41-beta.2', 'GPG_AGENT_INFO': '/home/pi/.gnupg/S.gpg-agent:0:1', 'GDMSESSION': 'Lubuntu', 'XDG_CONFIG_HOME': '/home/pi/.config', 'SAL_USE_VCLPLUGIN': 'gtk', 'PINGUINO_32_LIBS_PATH': '/opt/pinguino/v12/p32', 'XDG_RUNTIME_DIR': '/run/user/1000', 'PINGUINO_LIBS_PATH': '/opt/pinguino/v12', 'LC_IDENTIFICATION': 'en', 'LC_ADDRESS': 'en', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'XMODIFIERS': '', 'UPSTART_JOB': 'lxsession', 'PINGUINO_PYTHON': '2', 'XDG_DATA_DIRS': '/etc/xdg/lubuntu:/usr/share/gdm:/var/lib/menu-xdg:/usr/share/Lubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_SESSION_ID': 'c1', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-T91g8CPMfq', 'DEFAULTS_PATH': '/usr/share/gconf/Lubuntu.default.path', 'GTK_IM_MODULE': '', 'DESKTOP_SESSION': 'Lubuntu', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/995', 'XDG_CONFIG_DIRS': '/etc/xdg/lubuntu:/etc/xdg/xdg-Lubuntu:/usr/share/upstart/xdg:/etc/xdg', 'GNOME_KEYRING_PID': '', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.41-beta.2', 'PINGUINO_USERLIBS_PATH': '/opt/pinguino/v12/pinguinolibs', 'GDM_LANG': 'en\nen', 'LC_TELEPHONE': 'en', 'PINGUINO_INSTALL_PATH': '/opt/pinguino/v12', 'PAPERSIZE': 'a4', 'SHLVL': '0', 'PWD': '/home/pi', 'JOB': 'dbus', 'LC_PAPER': 'en', 'LC_NAME': 'en', 'XDG_MENU_PREFIX': 'lxde-', 'LC_TIME': 'en', 'LD_LIBRARY_PATH': '/usr/lib32:/usr/lib:/usr/lib64', 'PINGUINO_BOARD_ARCH': '8', 'PINGUINO_CAN_COMPILE': 'True', 'USER': 'pi'}

**Comment by MefhigosetH** [comment]
Sory, we not tested Pingüino IDE on Raspberry yet.
