### ISSUE TITLE
reserved.pickle missing/incorrect path

### ISSUE THREAD

**Issue by AlfredBroda** [PinguinoIDE/pinguino-ide#112]
File `reserved.pickle` seems to be missing, plus the path it is searched at is incorrect (I linked v12 to v13). The readme tells to check out into v13, but the code still refers to v12 (the splash screen says v13 is running).

Traceback (most recent call last):
  File "/home/fred/Pinguino/v13/pinguino-ide/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/home/fred/Pinguino/v13/pinguino-ide/pinguino/qtgui/ide/ide.py", line 132, in __init__
    self.PinguinoAutoCompleter = PinguinoAutoCompleter()
  File "/home/fred/Pinguino/v13/pinguino-ide/pinguino/qtgui/ide/custom_widgets/code_editor/autocompleter.py", line 59, in __init__
    with open(os.path.join(os.getenv("PINGUINO_USER_PATH"), "reserved.pickle"), "rb") as file_reserved:
FileNotFoundError: [Errno 2] Nie ma takiego pliku ani katalogu: '/home/fred/Pinguino/v12/reserved.pickle'

os.name: posix
os.environ: environ({'SHELL': '/bin/bash', 'SESSION_MANAGER': 'local/godzilla:@/tmp/.ICE-unix/4541,unix/godzilla:/tmp/.ICE-unix/4541', 'COLORTERM': 'truecolor', 'XDG_CONFIG_DIRS': '/etc/xdg', 'LESS': '-R -M --shift 5', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session1', 'HISTCONTROL': 'ignoreboth', 'JDK_HOME': '/etc/java-config-2/current-system-vm', 'CONFIG_PROTECT_MASK': '/etc/sandbox.d /etc/fonts/fonts.conf /etc/gentoo-release /etc/terminfo /etc/dconf /etc/ca-certificates.conf /etc/revdep-rebuild', 'GNOME_KEYRING_CONTROL': '/home/fred/.cache/keyring-RHRO8Z', 'LANGUAGE': 'en_GB:pl', 'JAVA_HOME': '/etc/java-config-2/current-system-vm', 'ANT_HOME': '/usr/share/ant', 'DESKTOP_SESSION': '/usr/share/xsessions/plasma', 'EDITOR': '/bin/nano', 'XDG_SEAT': 'seat0', 'PWD': '/home/fred/Pinguino/v13/pinguino-ide', 'CONFIG_PROTECT': '/usr/share/gnupg/qualified.txt /usr/share/config', 'LOGNAME': 'fred', 'XDG_SESSION_DESKTOP': 'KDE', 'XDG_SESSION_TYPE': 'x11', 'MANPATH': '/etc/java-config-2/current-system-vm/man:/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/man:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.30/man:/usr/lib/llvm/8/share/man:/etc/java-config-2/current-system-vm/man/:/usr/local/share/man:/usr/share/man', 'MC_TMPDIR': '/tmp/mc-fred', 'XAUTHORITY': '/home/fred/.Xauthority', 'OPENCL_PROFILE': 'nvidia', 'MC_SID': '7673', 'HOME': '/home/fred', 'SSH_ASKPASS': '/usr/bin/ksshaskpass', 'LANG': 'pl_PL.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.cfg=00;32:*.conf=00;32:*.diff=00;32:*.doc=00;32:*.ini=00;32:*.log=00;32:*.patch=00;32:*.pdf=00;32:*.ps=00;32:*.tex=00;32:*.txt=00;32:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'XDG_CURRENT_DESKTOP': 'KDE', 'VTE_VERSION': '5403', 'OPENGL_PROFILE': 'nvidia', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'KDE_SESSION_UID': '1000', 'INFOPATH': '/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/info:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.30/info:/usr/share/info', 'MOZ_GMP_PATH': '/usr/lib64/nsbrowser/plugins/gmp-gmpopenh264/system-installed', 'JAVAC': '/etc/java-config-2/current-system-vm/bin/javac', 'XDG_SESSION_CLASS': 'user', 'XDG_SESSION_COOKIE': 'godzilla-1568790086.429337-954914710', 'TERM': 'xterm-256color', 'LESSOPEN': '|lesspipe %s', 'USER': 'fred', 'KDE_SESSION_VERSION': '5', 'PAM_KWALLET5_LOGIN': '/tmp/kwallet5_fred.socket', 'MANPAGER': 'manpager', 'DISPLAY': ':0', 'SHLVL': '3', 'PAGER': '/usr/bin/less', 'XDG_VTNR': '7', 'GS_LIB': '/home/fred/.fonts', 'XDG_RUNTIME_DIR': '/var/run/user/1000', 'GCC_SPECS': '', 'GSETTINGS_BACKEND': 'dconf', 'QT_AUTO_SCREEN_SCALE_FACTOR': '0', 'XCURSOR_THEME': 'Oxygen_Black', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share', 'KDE_FULL_SESSION': 'true', 'GDK_BACKEND': 'x11', 'PATH': '/usr/lib/ccache/bin:/home/fred/go/bin:/home/fred/.local/bin:/usr/lib/ccache/bin:/home/fred/go/bin:/home/fred/.local/bin:/usr/lib/llvm/8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/opt/cuda/bin:/usr/local/go/bin:/usr/local/bin:/usr/local/go/bin:/usr/local/bin', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-oX53jEdr4y,guid=fe7bb7f5348470a51e702e225d81d646', 'MAIL': '/var/mail/fred', 'OLDPWD': '/home/fred/Pinguino/v13', '_': './pinguino-ide.py', 'PINGUINO_PYTHON': '3', 'PINGUINO_NAME': 'Pinguino IDE', 'PINGUINO_VERSION': '13.0.0', 'PINGUINO_MAJOR': '13', 'PINGUINO_MINOR': '0', 'PINGUINO_PATCH': '0', 'PINGUINO_FULLNAME': 'Pinguino IDE 13.0.0', 'PINGUINO_LIB': '/home/fred/Pinguino/v13/pinguino-ide/pinguino', 'PINGUINO_MODE': 'NORMAL', 'PINGUINO_OS_ARCH': '64bit', 'PINGUINO_OS_NAME': 'linux', 'PINGUINO_USER_PATH': '/home/fred/Pinguino/v12', 'PINGUINO_INSTALL_PATH': '/opt/pinguino/v12', 'PINGUINO_USERLIBS_PATH': '/opt/pinguino/v12/pinguinolibs', 'PINGUINO_LIBS_PATH': '/home/fred/Dvpt/pinguino/git-local/pinguino-libraries', 'PINGUINO_8_LIBS_PATH': '/home/fred/Dvpt/pinguino/git-local/pinguino-libraries/p8', 'PINGUINO_32_LIBS_PATH': '/home/fred/Dvpt/pinguino/git-local/pinguino-libraries/p32', 'PINGUINO_DEFAULT_FILES': '/home/fred/Pinguino/v12/local', 'PINGUINO_PROJECT': '', 'PINGUINO_BOARD_ARCH': '8', 'PINGUINO_CAN_COMPILE': 'False'})
os.uname: posix.uname_result(sysname='Linux', nodename='godzilla', release='5.0.5-gentoo', version='#1 SMP Sun Mar 31 23:42:40 CEST 2019', machine='x86_64')

**Comment by luvhines** [comment]
It says that the file "reserved.pickle" does not exist in the v13 directory, you can download that file right here in git, copy it in the directory, that fixes the problem
