### ISSUE TITLE
V.13 installation, compilation OK; unable to upload via USB

### ISSUE THREAD

**Issue by gopenelectronics** [PinguinoIDE/pinguino-ide#116]
After Remove  #    if sys.version_info.major >= 3:
    #        usbBuf = str(bytearray(usbBuf))
In both WriteUSB and RWEadUSB , I able to read device ID , But HEX Uploading i am getting Below Error , Not able to Upload Via USB
# ----------------------------------------------------------------------
    def usbWrite(self, device, usbBuf):
# ----------------------------------------------------------------------
        """ send bytes to the bootloader """
        self.add_report("%d Before bytes written." % len(usbBuf))
    #    if sys.version_info.major >= 3:
    #        usbBuf = str(bytearray(usbBuf))
        self.add_report("%d After bytes written." % len(usbBuf))
        if self.PYUSB_USE_CORE:
            sent_bytes = device.write(self.OUT_EP, usbBuf, self.TIMEOUT)
        else:
            sent_bytes = device.bulkWrite(self.OUT_EP, usbBuf, self.TIMEOUT)

        return sent_bytes

# ----------------------------------------------------------------------
    def usbRead(self, device):
# ----------------------------------------------------------------------
        """ read bytes from the bootloader
            whatever is returned, USB packet size is always 64 bytes
            long (self.MAXPACKETSIZE) in high speed mode
        """

        if self.PYUSB_USE_CORE:
            usbBuf = device.read(self.IN_EP, self.MAXPACKETSIZE, self.TIMEOUT)
        else:
            usbBuf = device.bulkRead(self.IN_EP, self.MAXPACKETSIZE, self.TIMEOUT)

  #      if sys.version_info.major >= 3:
  #          return str(bytearray(usbBuf))
  #      else:
            return usbBuf
        
        #return usbBuf

[INFO] compilation done
[INFO] Code size: 5096/29696 bytes (17.16% used)
[INFO] 1.953 seconds process time
[INFO] Looking for a Pinguino device ...
[INFO] Looking for a Pinguino device ...2
[INFO] Found device 0x04D8:0xFEAA
[INFO] Pinguino found ...
[INFO] Interface claimed
[INFO] Everything OK so far
[INFO] 64 Before bytes written.
[INFO] 64 After bytes written.

[INFO]  - with PIC18f4550 (id=0x1200, rev=0)
[INFO]  - with 29696 bytes free (29.00/32 KB)
[INFO]    from 0x00C00 to 0x08000
[INFO] 64 Before bytes written.
[INFO] 64 After bytes written.
[INFO]  - with USB bootloader v4.14
[INFO] Uploading user program ...
[INFO] 64 Before bytes written.
[INFO] 64 After bytes written.
[DEBUG] Traceback (most recent call last):

Traceback (most recent call last):
  File "C:\Users\cpn\AppData\Roaming\Python\Python38\site-packages\usb\_interop.py", line 92, in as_array
    return array.array('B', data)
TypeError: integer argument expected, got float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\ide\methods\decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\ide\methods\core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\pinguino_core\pinguino.py", line 137, in upload
    data = self.__upload__()
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 298, in __upload__
    result = self.upload_hex()
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\pinguino_core\uploader\uploader.py", line 235, in upload_hex
    self.uploader.uploadDevice(self.hex_file, self.board)
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 795, in uploadDevice
    status = self.writeHex(device, filename, board)
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 688, in writeHex
    self.flashErase(device, board.memstart, numBlocks)
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 339, in flashErase
    self.usbWrite(device, usbBuf)
  File "C:\Pinguino\V13_temp\pinguino-ide\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 202, in usbWrite
    sent_bytes = device.bulkWrite(self.OUT_EP, usbBuf, self.TIMEOUT)
  File "C:\Users\cpn\AppData\Roaming\Python\Python38\site-packages\usb\legacy.py", line 154, in bulkWrite
    return self.dev.write(endpoint, buffer, timeout)
  File "C:\Users\cpn\AppData\Roaming\Python\Python38\site-packages\usb\core.py", line 947, in write
    _interop.as_array(data),
  File "C:\Users\cpn\AppData\Roaming\Python\Python38\site-packages\usb\_interop.py", line 97, in as_array
    a.fromstring(data) # deprecated since 3.2
TypeError: a bytes-like object is required, not 'list'

**Comment by gopenelectronics** [comment]
Problem Fixed after  convert float into integer value  (numBlocks = int(numBlocks);)Now Uploading user program into my board .....



Code Chages

writeHex
(numBlocks = int(numBlocks)

WriteUsb
#    if sys.version_info.major >= 3:
    #        usbBuf = str(bytearray(usbBuf))

ReadUsb
  #      if sys.version_info.major >= 3:
  #          return str(bytearray(usbBuf))
  #      else:

**Comment by esternin** [comment]
I think you meant to respond to issue #114 but opened a new issue instead.  Perhaps we could merge this one into #114?

In any case I am not sure I understand your "fix".  You seem to imply that one should cast the variable `numBlocks` as `int` some place, but I am not recognizing the place in the code you are describing. Could you point out which one of these you are talking about?
```
$ grep -R numBlocks ./
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:    2015-09-08 - RB - fixed numBlocks > numBlocksMax when used with XC8
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:    def flashErase(self, device, address, numBlocks):
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:        """ erase numBlocks of flash memory """
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:        usbBuf[self.BOOT_SIZE] = numBlocks
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:        #usbBuf[self.BOOT_SIZE] = int(numBlocks)
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:        numBlocksMax = (MEMEND      - MEMSTART) / eraseBlockSize
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:        numBlocks    = (max_address - MEMSTART) / eraseBlockSize
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:        #self.add_report("numBlocks    : %d" % numBlocks)
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:        #self.add_report("numBlocksMax : %d" % numBlocksMax)
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:        if  numBlocks > numBlocksMax:
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:            numBlocks = numBlocksMax
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:        if  numBlocks < 256:
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:            self.flashErase(device, board.memstart, numBlocks)
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:            numBlocks = numBlocks - 255
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:            self.flashErase(device, upperAddress, numBlocks)
```

Your first suggestion, replacing `usbBuf = str(bytearray(usbBuf))` with `return str(bytearray(usbBuf))` seems to only match one place in the code, line 197 in uploader8.py.  I made this change (line 220 already uses this form of return, so I did not do anything there), but it made no difference to the errors:
```
$ grep -R -A 2 -B 2 -n sys.version_info.major ./
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py-194-        """ send bytes to the bootloader """
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py-195-
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:196:        if sys.version_info.major >= 3:
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py-197-            return str(bytearray(usbBuf))
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py-198-#            usbBuf = str(bytearray(usbBuf))
--
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py-218-            usbBuf = device.bulkRead(self.IN_EP, self.MAXPACKETSIZE, self.TIMEOUT)
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py-219-
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py:220:        if sys.version_info.major >= 3:
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py-221-            return str(bytearray(usbBuf))
./pinguino-ide/pinguino/qtgui/pinguino_core/uploader/uploader8.py-222-        else:
```
Could you please clarify how you fixed things?  Also, what is the target board you are using?
