### ISSUE TITLE
Where do I found "reserved.pickle" ?

### ISSUE THREAD

**Issue by Keuronde** [PinguinoIDE/pinguino-ide#118]
Traceback (most recent call last):
  File "/home/samuel/Pinguino/v13/pinguino-ide/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/home/samuel/Pinguino/v13/pinguino-ide/pinguino/qtgui/ide/ide.py", line 132, in __init__
    self.PinguinoAutoCompleter = PinguinoAutoCompleter()
  File "/home/samuel/Pinguino/v13/pinguino-ide/pinguino/qtgui/ide/custom_widgets/code_editor/autocompleter.py", line 59, in __init__
    with open(os.path.join(os.getenv("PINGUINO_USER_PATH"), "reserved.pickle"), "rb") as file_reserved:
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/samuel/Pinguino/v13/reserved.pickle'

os.name: posix
os.environ: environ({'SHELL': '/bin/bash', 'SESSION_MANAGER': 'local/Heremia:@/tmp/.ICE-unix/1256,unix/Heremia:/tmp/.ICE-unix/1256', 'QT_ACCESSIBILITY': '1', 'COLORTERM': 'truecolor', 'XDG_MENU_PREFIX': 'gnome-', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'DESKTOP_SESSION': 'gnome', 'GTK_MODULES': 'gail:atk-bridge', 'XDG_SEAT': 'seat0', 'PWD': '/home/samuel/Pinguino/v13', 'XDG_SESSION_DESKTOP': 'gnome', 'LOGNAME': 'samuel', 'XDG_SESSION_TYPE': 'wayland', 'GDM_LANG': 'fr_FR.UTF-8', 'HOME': '/home/samuel', 'USERNAME': 'samuel', 'LANG': 'fr_FR.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'XDG_CURRENT_DESKTOP': 'GNOME', 'VTE_VERSION': '5402', 'WAYLAND_DISPLAY': 'wayland-0', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/0e4b381d_d575_4e27_aa41_d1b38e3bc92e', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm-256color', 'USER': 'samuel', 'GNOME_TERMINAL_SERVICE': ':1.75', 'DISPLAY': ':0', 'SHLVL': '1', 'XDG_VTNR': '2', 'DESKTOP_AUTOSTART_ID': '10657cc797de70816d15899162863336100000012560007', 'XDG_SESSION_ID': '2', 'XDG_RUNTIME_DIR': '/run/user/1000', 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games', 'GDMSESSION': 'gnome', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'OLDPWD': '/home/samuel/Pinguino/v13/pinguino-ide/pinguino/qtgui/config', '_': '/usr/bin/python3', 'PINGUINO_PYTHON': '3', 'PINGUINO_NAME': 'Pinguino IDE', 'PINGUINO_VERSION': '13.0.0', 'PINGUINO_MAJOR': '13', 'PINGUINO_MINOR': '0', 'PINGUINO_PATCH': '0', 'PINGUINO_FULLNAME': 'Pinguino IDE 13.0.0', 'PINGUINO_LIB': '/home/samuel/Pinguino/v13/pinguino-ide/pinguino', 'PYSIDE_PACKAGE_DIR': '/usr/lib/python3/dist-packages/PySide2', 'PINGUINO_MODE': 'NORMAL', 'PINGUINO_OS_ARCH': '64bit', 'PINGUINO_OS_NAME': 'linux', 'PINGUINO_USER_PATH': '/home/samuel/Pinguino/v13', 'PINGUINO_INSTALL_PATH': '/opt/pinguino/v13', 'PINGUINO_USERLIBS_PATH': '/opt/pinguino/v13/pinguinolibs', 'PINGUINO_LIBS_PATH': '/home/yeison/Development/Pinguino/pinguino-libraries', 'PINGUINO_8_LIBS_PATH': '/home/yeison/Development/Pinguino/pinguino-libraries/p8', 'PINGUINO_32_LIBS_PATH': '/home/yeison/Development/Pinguino/pinguino-libraries/p32', 'PINGUINO_DEFAULT_FILES': '/home/samuel/Pinguino/v13/local', 'PINGUINO_PROJECT': '', 'PINGUINO_BOARD_ARCH': '8', 'PINGUINO_CAN_COMPILE': 'False'})
os.uname: posix.uname_result(sysname='Linux', nodename='Heremia', release='5.2.0-0.bpo.2-amd64', version='#1 SMP Debian 5.2.9-2~bpo10+1 (2019-08-25)', machine='x86_64')

**Comment by Keuronde** [comment]
I found it here : https://github.com/PinguinoIDE/pinguino-ide-tk/blob/master/tkgui/config/reserved.pickle
But I think it should be delivered with the main project

**Comment by luzemario** [comment]
Using "Reset IDE configuration" with v13 causes this issue. The file is removed but not created again, so there is an error at every start:

``` Traceback (most recent call last):
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/ide/ide.py", line 132, in __init__
    self.PinguinoAutoCompleter = PinguinoAutoCompleter()
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/ide/custom_widgets/code_editor/autocompleter.py", line 59, in __init__
    with open(os.path.join(os.getenv("PINGUINO_USER_PATH"), "reserved.pickle"), "rb") as file_reserved:
FileNotFoundError: [Errno 2] Arquivo ou diretório não encontrado: '/home/luzemario/Pinguino/v13/reserved.pickle'
```

**Comment by luzemario** [comment]
Is important to note: when there is not paths.conf, Pinguino 13 tries to access '/home/regis' from @rblanchot developer... :-)

**Comment by MefhigosetH** [comment]
Thanks for the information.

Please, make backup of any user generated *.pde file (if exists) inside the `~/Pinguino` folder, before delete.
