### ISSUE TITLE
ElemetaryOS latest version. Default install. Problem wih python 2.7 and examples problems does not load

### ISSUE THREAD

**Issue by AngelPortal** [PinguinoIDE/pinguino-ide#123]
Traceback (most recent call last):
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/ide.py", line 132, in __init__
    self.PinguinoAutoCompleter = PinguinoAutoCompleter()
  File "/opt/pinguino/v12/pinguino/qtgui/ide/custom_widgets/code_editor/autocompleter.py", line 59, in __init__
    with open(os.path.join(os.getenv("PINGUINO_USER_PATH"), "reserved.pickle"), "rb") as file_reserved:
IOError: [Errno 2] Arquivo ou diretório inexistente: '/home/angel/Pinguino/v12/reserved.pickle'

os.uname: ('Linux', 'PRESARIOCQ18', '5.4.0-52-generic', '#57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020', 'x86_64')
os.name: posix
os.environ: {'XAUTHORITY': '/home/angel/.Xauthority', 'PINGUINO_USER_PATH': '/home/angel/Pinguino/v12', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/angel', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'PINGUINO_DEFAULT_FILES': '/home/angel/Pinguino/v12/local', 'PINGUINO_NAME': 'Pinguino IDE', 'XDG_CURRENT_DESKTOP': 'Pantheon', 'XDG_SESSION_TYPE': 'x11', 'PINGUINO_BOARD_ARCH': '8', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'angel', 'XDG_SEAT': 'seat0', 'HOME': '/home/angel', 'XDG_VTNR': '7', 'PATH': '/home/angel/.local/bin:/home/angel/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'PINGUINO_8_LIBS_PATH': '/opt/pinguino/v12/p8', 'DISPLAY': ':0', 'SSH_AGENT_PID': '2442', 'LANG': 'pt_BR.UTF-8', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'QT_STYLE_OVERRIDE': 'adwaita', 'LANGUAGE': 'pt_BR:pt:en', 'SESSION_MANAGER': 'local/PRESARIOCQ18:@/tmp/.ICE-unix/2292,unix/PRESARIOCQ18:/tmp/.ICE-unix/2292', 'SHLVL': '0', 'GTK3_MODULES': 'pantheon-filechooser-module', 'QT_QPA_PLATFORMTHEME': 'gtk3', 'PINGUINO_OS_ARCH': '64bit', 'GTK_CSD': '1', 'PINGUINO_PROJECT': '', 'QT_ACCESSIBILITY': '1', 'PINGUINO_PYTHON': '2', 'XMODIFIERS': '@im=ibus', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '10069', 'PINGUINO_VERSION': '12.0.41-beta.2', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'KICAD_PATH': '/usr/share/kicad', 'XDG_SESSION_DESKTOP': 'pantheon', 'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/pinguino12.desktop', 'PINGUINO_32_LIBS_PATH': '/opt/pinguino/v12/p32', 'XDG_RUNTIME_DIR': '/run/user/1000', 'PINGUINO_LIBS_PATH': '/opt/pinguino/v12', 'PINGUINO_LIB': '/opt/pinguino/v12/pinguino', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'GDMSESSION': 'pantheon', 'PINGUINO_MODE': 'NORMAL', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_SESSION_ID': 'c2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'GTK_MODULES': 'gail:atk-bridge', 'DESKTOP_SESSION': 'pantheon', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-pantheon:/etc/xdg', 'KIGITHUB': 'https://github.com/KiCad', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.41-beta.2', 'PINGUINO_USERLIBS_PATH': '/opt/pinguino/v12/pinguinolibs', 'PINGUINO_OS_NAME': 'linux', 'GDM_LANG': 'pt_BR', 'PINGUINO_INSTALL_PATH': '/opt/pinguino/v12', 'QSYS_ROOTDIR': '/home/angel/intelFPGA_lite/20.1/quartus/sopc_builder/bin', 'XDG_DATA_DIRS': '/usr/share/gnome:/usr/share/pantheon:/home/angel/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share', 'PWD': '/home/angel', 'XDG_MENU_PREFIX': 'gnome-', 'PINGUINO_CAN_COMPILE': 'False', 'USER': 'angel'}

**Comment by MefhigosetH** [comment]
Dear,

Please, check this comment, as seem same issue than this one...

https://github.com/PinguinoIDE/pinguino-ide/issues/118#issuecomment-633256747
