### ISSUE TITLE
Is there a list of supported boards?

### ISSUE THREAD

**Issue by agrimagsrl** [PinguinoIDE/pinguino-ide#126]
I never used PIC32 and I'm looking for something compatible with Arduino language. I still don't have a board, I want to buy one that's well supported: is there a list of supported boards?

**Comment by HavenTech** [comment]
If you are just looking for something to learn with, then Pinguino would be fine. However, if you are planning something along professional lines, then you may want to consider the Digilent PIC32 range: https://store.digilentinc.com/embedded-processors/by-technology/ 

 

Regards 

 




Michael Havenga, Haventechnik

CELL: 0827728050

Twitter:  <https://twitter.com/HavenTechnik> @HavenTechnik

Instagram: haven_tech

LinkedIn: Personal Profile <https://www.linkedin.com/in/michael-havenga-4537ba54/> 

WEB: www.haventechnik.com <http://www.haventechnik.com/>  

Email: michaelh@haventechnik.com <mailto:michaelh@haventechnik.com>

**Comment by MefhigosetH** [comment]
Dear @agrimagsrl , thanks for your interest on Pinguino Project.

The list of PIC32 actually supported by the Pinguino Project, resides on the Pinguino IDE v13 sidebar (right hand), inside **Board** tab. You need to select **Architecture: 32-bits** on the first option:

/tmp/pinguino-boards.png

I would add this info on the website docs soon.

Best regards.

**Comment by agrimagsrl** [comment]
Thanks for the response, I will take a look.
