### ISSUE TITLE
No boards?

### ISSUE THREAD

**Issue by Hairyloon** [PinguinoIDE/pinguino-ide#128]
You don't seem to have anything listed on your boards page. I would expect to see at least schematics...

**Comment by MefhigosetH** [comment]
Dear @Hairyloon ,

Thank for your contact.

Yes, it's true. We are adding new content to the site, but it's under construction yet.

Keep turned on.

**Comment by MefhigosetH** [comment]
Please, see https://pinguino.cc/pinguino-boards/supported-boards-8.html
