### ISSUE TITLE
Installation of v13 on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by swhomans** [PinguinoIDE/pinguino-ide#129]
Hi Folks,

I'm a retired professor of biophysics. I have been using the Pinguino environment successfully for a number of years with my hobby which is amateur radio (you can see my projects at stevewhomans.wordpress.com). I recently tried installing Pinguino v13 using a fresh install of Ubuntu 20.04 running virtualbox 6.1 (windows host), python 3.8.5 and pips 20.0.2. I encountered a couple of trivial issues during the install that I thought I should share:

1. I needed to install libxcb-xinerama0 to get the GUI running
2. The .conf file generated by the install script does not point to the correct directory for the P32 libraries.

I resolved the second problem by editing the .conf file directly, but it might be useful to fix this error in the next version of the installer.

A further problem that I have not been able to fix concerns interrupts. I first noticed this with my code but it is also demonstrated by attempting to compile the example under "08.Interrupt" entitled "P32-FrequencyMeter80MHz.pde" (using Pinguino P32 OTG board). The linker complains that the ISR is too large. I can compile my own code (and the example just mentioned) with no problem using Pinguino X4 rev959 (on windows), but I have never been able to compile this code with later versions. Since X4 has been fine for my needs I have not pursued the problem, but it would be good to resolve it moving forwards perhaps. I'm not an expert but it seems to me that later versions are trying to insert and run the ISR code within the interrupt vector table space, rather than creating a pointer to the ISR. Does anyone have any thoughts? Many thanks! Regards, Steve H.

_Originally posted by @swhomans in https://github.com/PinguinoIDE/pinguinoide.github.io/discussions/5#discussioncomment-611184_

**Comment by MefhigosetH** [comment]
Fixed on tis PR https://github.com/PinguinoIDE/pinguino-installers/pull/20

Will be deployed on the next version of Linux Installer.

**Comment by swhomans** [comment]
Many thanks. If anyone in the community knows how to fix the interrupt issue, I’d be happy to work through it

**Comment by swhomans** [comment]
Interrupt issue resolved. I am using the following construct with compiler directives to enable an external interrupt on PIC32:

//interrupt declarations
 void _ _attribute__ ((nomips16)) ISR_wrapper_vector_7(void) _ _attribute__ ((section (".vector_7")));
// vector 7 is the external input 1 interrupt vector - see datasheet table 7-1
// INT1 is on pin CON4-D6 on Pinguino-Pic32-OTG (RD8)
 void _ _attribute__ ((nomips16)) Int1Interrupt(void) _ _attribute__ ((interrupt));
 void _ _attribute__ ((nomips16)) ISR_wrapper_vector_7(void) { Int1Interrupt(); }
 
This compiles with no problem on version X4 rev 959 (Windows), but fails on v11 onwards. In the latter case the compiler correctly locates the wrapper vector to section 7 of the interrupt vector table, but then tries to load the ISR in that location too. There is insufficient space, hence the linker error. The optimization level of the compiler in X.4 defaults to "-Os", whereas it defaults to "-O2" in later releases. Compiling under the "-Os" level of optimization in v11 onwards results in error free compilation. It's not clear to me why the "-Os" level of optimization is necessary here (the two levels differ in only a few options that seem unrelated to the issue in hand) - but understanding this is a project for another day....
