### ISSUE TITLE
Error: BadWindow

### ISSUE THREAD

**Issue by rblanchot** [PinguinoIDE/pinguino-ide#25]
Debian Jessie/Sid 64-bit / XFCE4.10
The IDE starts OK but when I type something (but nothing special) the program exits.
I have 2 screens connected on my computer, the program exits only when on one of them (1920x1080) :

Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 1 (X_CreateWindow)
  Resource id:  0x0
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 18 (X_ChangeProperty)
  Resource id:  0x0
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 19 (X_DeleteProperty)
  Resource id:  0x0
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 18 (X_ChangeProperty)
  Resource id:  0x3a0007d
Segmentation fault

**Comment by MefhigosetH** [comment]
No v11 support now
