### ISSUE TITLE
No ICSP mode available

### ISSUE THREAD

**Issue by rblanchot** [PinguinoIDE/pinguino-ide#27]
Selecting ICSP mode has no effect on compilation.
Back on the Board Configuration Menu, the bootloader Mode is still active.

**Comment by rblanchot** [comment]
Ok. Thanks.
However I notices the Board Configuration Window doesn't close after Accept button has been pressed ...

**Comment by YeisonEng** [comment]
This "raise Exception" must no be there, was removed.
