### ISSUE TITLE
define.h issue

### ISSUE THREAD

**Issue by rblanchot** [PinguinoIDE/pinguino-ide#31]
Test done with a Pinguino 32MX250 but same error occurs with all boards.

    Serial.print("i=");
    Serial.printNumber(i++, DEC);
    Serial.print("\r\n");

is replaced by : 

    serial1print("i=");
    serial1printNumber(i++, DEC);
    serial1print("\r\n");

Compilation leads to undefined reference to `serial1printNumber'

In pserial.pdl32 :
Serial.print serial1print#include \<serial1.c\>#define SERIALPRINT
Serial.printNumber serial1printNumber#include \<serial1.c\>#define SERIALPRINTNUMBER

The problems comes from define.h where I expect to find #define SERIALPRINT and #define SERIALPRINTNUMBER but there is only #define SERIALPRINT.

Note that compilation is fine if I use only Serial.printNumber (no Serial.print).

**Comment by rblanchot** [comment]
See also :  lcd.printf - Too many parameters #5 (https://github.com/PinguinoIDE/pinguino-libraries/issues/5)

**Comment by YeisonEng** [comment]
The bug is in replace functions, this was replaced by regex.sub

**Comment by rblanchot** [comment]
I reported your last changes but now I can't compile anymore.

**Comment by rblanchot** [comment]
Fixed
