### ISSUE TITLE
Can't link in Ubuntu i386 for board PIC32 Pinguino T795

### ISSUE THREAD

**Issue by mobluse** [PinguinoIDE/pinguino-ide#36]
PinguinoIDE can't link BareMinimum.pde in Ubuntu 14.04 LTS i386 for board PIC32 Pinguino T795: gcc/mips-elf/4.9.2/…/mips-elf/bin/ld: cannot find -lgcc

**Comment by rblanchot** [comment]
How did you installed the IDE ? With the installer script ?

**Comment by mobluse** [comment]
Yes, I used installer.sh according to the instructions.
