### ISSUE TITLE
Can't start from menu in Ubuntu or Raspbian

### ISSUE THREAD

**Issue by mobluse** [PinguinoIDE/pinguino-ide#37]
PinguinoIDE (installed today) can't start from menu in Ubuntu 14.04 for i386 or Raspbian latest for Raspberry Pi, but for different reasons. Ubuntu: needs sudo; Raspbian: folder string in menu item is empty "".

Now I need to start it from the command-line using sudo in Ubuntu and without sudo in Raspbian. I fixed manually in Raspbian by adding a folder /home/pi to the menu item. I would like to not use sudo in Ubuntu for security reasons and also not create more files owned by root. I have a menu in Ubuntu since I use Classic Menu Indicator, but starting from the Ubuntu search button also doesn't work for the same reason, I presume.

**Comment by rblanchot** [comment]
If you want to install the IDE in your own folder then you have to indicate the path in Settings > System Paths.
If it's not enough take a look at paths.cfg and qtgui/config/pinguino.linux.conf.

**Comment by MefhigosetH** [comment]
No user feedback
