### ISSUE TITLE
New preprocessing problem with Audio library

### ISSUE THREAD

**Issue by gtcbreizh** [PinguinoIDE/pinguino-ide#38]
The following statement is badly translated :
        Audio.tone( CCP2, melody[ thisNote], noteDuration);
into :
        Audio_Audio_Tone( CCP2, melody[ thisNote], noteDuration);
instead of :
        Audio_tone( CCP2, melody[ thisNote], noteDuration);
Same bad translation with this :
    Audio.noTone( CCP2);
into :
    Audio_Audio_noTone( CCP2);
instead of :
    Audio_noTone( CCP2);

To better understand, here is a partial content of audio.pdl
Audio.tone Audio_tone#include <audio.c>
Audio.noTone Audio_noTone#include <audio.c>

tone Audio_tone#include <audio.c>
noTone Audio_noTone#include <audio.c>

Nota Bene :It works with the qtgui dated january 2015

**Comment by YeisonEng** [comment]
After to update PinguinoIDE with the `installer.sh` I notice that I have `audio.c` and `sound.c` and their `.pdl` with the same definitions.
This is probably not the cause of the error, but I can not debug.
cc @rblanchot

**Comment by gtcbreizh** [comment]
Thanks Yeison.
I removed the “alias” note and noTone from sound.pdl and so the compilation works.
Sorry for this inconvenience.
Hasta pronto,
André

**Comment by gtcbreizh** [comment]
I put a new issue #39 on Github with a clue (no translation for TEMPERATURE, data found in 1wire.pdl to translate into DS18B20_Temperature).
Thanks in advance.
Hasta pronto
André
