### ISSUE TITLE
New preprocessing problem with address (here &t) as statement parameters

### ISSUE THREAD

**Issue by gtcbreizh** [PinguinoIDE/pinguino-ide#39]
I cannot compile the pde below with the 2 last pinguino_tools.py dated 20/02/ and 13/02/2015.
Message : ERROR: 7: token-> 't'; column 14.
It works with the previous  pinguino_tools.py dated on 03/02/2015.
I think that the & character is badly preprocessed
#define ONEWIREBUS	6						// DQ line			
void setup()
{
}
void loop()
{
	TEMPERATURE t;
	if (DS18B20.read(ONEWIREBUS, SKIPROM, RES12BIT, &t))
	{
		if (t.sign) CDC.printf("-");
		CDC.printf("%d.%d°C \r", t.integer, t.fraction);
	}
	delay(1000);
}
---------------------------------------------------------------------------------------------
1wire.pdl contents :
DS18B20.read DS18B20Read#include <18b20.c>

user.c is :
void setup()
{
}
void loop()
{
	TEMPERATURE t;
	if (DS18B20Read(ONEWIREBUS, SKIPROM, RES12BIT, &t))
	{
		if (t.sign) CDCprintf("-");
		CDCprintf("<PINGUINO_STRING>", t.integer, t.fraction);
	}
	Delayms(1000);
}
define.h :
#define CDCPRINTF
#define ONEWIREBUS	6						
#include <18b20.c>
#include <__cdc.c>
#include <delayms.c>

**Comment by gtcbreizh** [comment]
Read 
1wire.pdl contents :
DS18B20.read DS18B20Read#include <18b20.c>

**Comment by gtcbreizh** [comment]
I understood the bug.
1wire.pdl contents :
TEMPERATURE DS18B20_Temperature#include <18b20.c>
and with the last pinguino_tools.py TEMPERATURE is not translated as you can see above in user.c.
Please could you repair ?

**Comment by YeisonEng** [comment]
Hi,
Can you test the last commit.
