### ISSUE TITLE
download of ide not working

### ISSUE THREAD

**Issue by fcwpinguino** [PinguinoIDE/pinguino-ide#40]
@rblanchot , @YeisonEng
when i downloaded the ide on a debian jessie 64 bit machine this is what i receive and the ide says compilers missing.

fred

---

 Pinguino IDE Installation Script
 Regis Blanchot - rblanchot@pinguino.cc
 Last update 16-12-2014

---

 Host is a 64-bit GNU/Linux.
 What compiler(s) do you want to install ?
 1) none of them (default)
 2) the  8-bit (PIC18F)  compiler only
 3) the 32-bit (PIC32MX) compiler only
 4) both 8- and 32-bit compilers

> 3
>  Downloading packages ...
>   99% [===============================================.]

 Installing packages ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive pinguino-linux64-gcc-mips-elf.deb (--install):
 cannot copy extracted data for './usr/bin/p32-as' to '/usr/bin/p32-as.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 pinguino-linux64-gcc-mips-elf.deb
chmod: cannot access ‘/usr/bin/p32-*’: No such file or directory
  99% [===============================================.]

WARNING:root:Copying: /root/.pinguino/source/crt0iz.c
WARNING:root:Copying: /root/.pinguino/source/crt0i.c
WARNING:root:Copying: /root/.pinguino/source/main32.c
WARNING:root:Copying: /root/.pinguino/source/Makefile32.windows
WARNING:root:Copying: /root/.pinguino/source/common_types.h
WARNING:root:Copying: /root/.pinguino/source/main.c
WARNING:root:Copying: /root/.pinguino/source/crt0.c
WARNING:root:Copying: /root/.pinguino/source/Makefile32.linux
WARNING:root:Copying: /root/.pinguino/source/main32.cpp
WARNING:root:Copying: /root/.pinguino/source/Makefile8.linux
WARNING:root:Copying: /root/.pinguino/source/config.h
WARNING:root:Copying: /root/.pinguino/source/crt0iPinguino.c
WARNING:root:Copying: /root/.pinguino/source/Makefile32.macosx
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/32MX795F512H.o
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/32MX460F512L.o
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/32MX270F256B.o
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/processor.o
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/LICENSE
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/32MX220F032D.o
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/32MX795F512L.o
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/32MX250F128B.o
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/32MX220F032B.o
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/32MX440F256H.o
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/usb/libcdc220.a
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/usb/libcdc.a
WARNING:root:Copying: /root/.pinguino/source/obj/non-free/usb/libadb.a
 Installation complete.
fred@debian:~$

**Comment by fcwpinguino** [comment]
i copied the ide from my other computer and i have it working now

**Comment by MefhigosetH** [comment]
Resolved.
