### ISSUE TITLE
Preprocessor error with PIC registers : bits -> Bits

### ISSUE THREAD

**Issue by rblanchot** [PinguinoIDE/pinguino-ide#41]
Use of PIC registers instructions like TRISAbits.TRISA4 = 0; leads to error.
The preprocessor replaces TRISA<b>b</b>its.TRISA4 by TRISA<b>B</b>its.TRISA4 (bits -> Bits).

**Comment by YeisonEng** [comment]
@rblanchot Where is TRISAbits.TRISA4?, in a pdl?, I can not find it.

**Comment by rblanchot** [comment]
TRISAbits.TRISA4 (this is just an example) is pure C syntax where TRISA is
a PIC register (though actually an address in the PIC memory) and TRISA4 a
bit of this register. All these structures are define in pic18fxxxxx.h or
pic32mxxxxx.h header files.
The preprocessor shouldn't try to translate bits in Bits because it is not
a whole word (at least the character before is not a space).


2015-03-09 18:46 GMT+01:00 Yeison Cardona <notifications@github.com>:

**Comment by YeisonEng** [comment]
Ok I understand, fixed in the [commit 49788db9dd](https://github.com/PinguinoIDE/pinguino-ide/commit/49788db9dd0a45ff76a15bcd4bef21e6e6b5f21c).
