### ISSUE TITLE
error compiling after recent update

### ISSUE THREAD

**Issue by fcwpinguino** [PinguinoIDE/pinguino-ide#42]
Regis,
 After the recent update 3-11-2015  the pde's compile with errors.

thank you
fred

**Comment by fcwpinguino** [comment]
regis
this is the button example and the error i get when compiling after the new update, this happens on most of the examples.
thank you 
fred

/dvpt/pinguino/git-copy/pinguino-compilers/sources/sdcc/src/pic16/main.c:701 setting interrupt vector addresses 0xc00
Processor: 18f4550
sdcc: Calling preprocessor...
sdcc: Generating code...
/home/fred/.pinguino/source/user.c:29: syntax error: token -> 'buttonPin' ; column 18

**Comment by YeisonEng** [comment]
Hi @fcwpinguino 
Try with the last version, must work now.

**Comment by fcwpinguino** [comment]
Yeison,
 No i still get the same error using the button example.
fred

**Comment by YeisonEng** [comment]
@fcwpinguino 
I mean the version on GitHub, not the installer, right?

**Comment by fcwpinguino** [comment]
oh , i did the installer  let me try
fred



-----Original Message-----

**Comment by fcwpinguino** [comment]
Yeison,
 it works now.
thank you
fred 



-----Original Message-----

**Comment by fcwpinguino** [comment]
Yeison,
 are you updating the installer files?
fred



-----Original Message-----

**Comment by YeisonEng** [comment]
@fcwpinguino 
No, that does Regis

**Comment by fcwpinguino** [comment]
ok thank you



-----Original Message-----
