### ISSUE TITLE
Pinguino 11.0-Beta3 with Linux error on upload 

### ISSUE THREAD

**Issue by lopezignacio** [PinguinoIDE/pinguino-ide#47]
Hi,

I have Pinguino 11.0-Beta3 with Linux error on upload. Compile ok but not upload with this error:

[OUT] Board: Pinguino 4550
[OUT] Proc: 18f4550
[OUT] Arch: 8
[OUT] Bootloader: v4
[DEBUG] Starting 'verify' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Starting 'preprocess' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Starting 'remove_comments' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'remove_comments': 0.00 s
[DEBUG] Ending 'remove_comments'
[DEBUG] Starting 'remove_comments' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'remove_comments': 0.00 s
[DEBUG] Ending 'remove_comments'
[DEBUG] Starting 'get_regobject_libinstructions' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Starting 'read_lib' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'read_lib': 0.11 s
[DEBUG] Ending 'read_lib'
[DEBUG] Time spent for 'get_regobject_libinstructions': 0.12 s
[DEBUG] Ending 'get_regobject_libinstructions'
[DEBUG] Starting 'replace_word' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'replace_word': 0.03 s
[DEBUG] Ending 'replace_word'
[DEBUG] Time spent for 'preprocess': 0.18 s
[DEBUG] Ending 'preprocess'
[DEBUG] Starting 'compile' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'compile': 0.53 s
[DEBUG] Ending 'compile'
[DEBUG] Starting 'link' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Time spent for 'link': 0.17 s
[DEBUG] Ending 'link'
[DEBUG] Time spent for 'verify': 0.91 s
[DEBUG] Ending 'verify'
[OUT] Compilación terminada
[OUT] Code size: 16746 / 29696 bytes (56% used)
[OUT] 0.907 segundos de procesamiento
[DEBUG] Starting '__upload__' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Starting 'upload' from 'qtgui.pinguino_api.uploader.uploader'
[DEBUG] Looking for a Pinguino device ...
[DEBUG] Found device 0x1D6B:0x0003
[DEBUG] Found device 0x1D6B:0x0002
[DEBUG] Found device 0x04D8:0xFEAA
[DEBUG] Pinguino found ...
[DEBUG] OS is linux
[DEBUG] Configuration set
[DEBUG] Interface claimed
[DEBUG] Everything OK so far
[DEBUG]  - with PIC18f4550 (id=1200)
[DEBUG]  - with 29696 bytes free (29 KB)
[DEBUG]    from 0x00C00 to 0x08000
[DEBUG]  - with USB bootloader v4.14
[DEBUG] Uploading user program ...
[DEBUG] Traceback (most recent call last):
[DEBUG]   File '/usr/share/pinguino-11/qtgui/pinguino_api/tools.py', line 23, in inset
[DEBUG]     ret = f(*args, **kwaargs)
[DEBUG]   File '/usr/share/pinguino-11/qtgui/pinguino_api/uploader/uploader.py', line 177, in upload
[DEBUG]     self.uploader.uploadDevice(self.hexfile, self.board)
[DEBUG]   File '/usr/share/pinguino-11/qtgui/pinguino_api/uploader/uploader8.py', line 514, in uploadDevice
[DEBUG]     status = self.writeHex(handle, filename, board)
[DEBUG]   File '/usr/share/pinguino-11/qtgui/pinguino_api/uploader/uploader8.py', line 430, in writeHex
[DEBUG]     self.eraseFlash(board.memstart, 255)
[DEBUG] TypeError: eraseFlash() takes exactly 4 arguments (3 given)
[DEBUG] 
[DEBUG] Traceback (most recent call last):
[DEBUG]   File '/usr/share/pinguino-11/qtgui/pinguino_api/tools.py', line 23, in inset
[DEBUG]     ret = f(*args, **kwaargs)
[DEBUG]   File '/usr/share/pinguino-11/qtgui/pinguino_api/pinguino_tools.py', line 228, in __upload__
[DEBUG]     result = filter(lambda line: not line.isspace(), result)
[DEBUG] TypeError: 'NoneType' object is not iterable
[DEBUG] 
>>> 

thx!

**Comment by lopezignacio** [comment]
The specific command that generates the error is:
lcd.setCursor(0, 0);
However, this command does not generate an error if I do:
lcd.home();

thx;

Spanish:
Es algo raro. Compila correctamente y no encuentra errores. Cuando me propone quemar el micro y aceptar, es ahi donde surje este error. No se si es un error en la libreria lcd o algo en el HEX generado.

Muchas gracias por su tiempo!

Buena Vida!

**Comment by YeisonEng** [comment]
Un saludo @lopezignacio 
Intenta con la última versión disponible en el repositorio.
