### ISSUE TITLE
Wheel not installed. Error code was: error!

### ISSUE THREAD

**Issue by gam01hr** [PinguinoIDE/pinguino-ide#48]
[file I'm installing]
pinguino-11.2015.02.02-setup.exe
[windows]
Windows 7 Home Premium
[note1]
my HDD starts with drive E: , windows is installed on drive E:, drive C: is not available at all.
What shoud I do?
[output]
Output folder: C:\pinguino-11
Python v2.7 not detected in your system. Installing it...
Output folder: E:\Users\zb\AppData\Local\Temp
Extract: python-2.7.7.msi... 100%
Execute: "msiexec" /i "E:\Users\zb\AppData\Local\Temp\python-2.7.7.msi"
Python v2.7 installed.
Delete file: E:\Users\zb\AppData\Local\Temp\python-2.7.7.msi
PyPIP not detected in your system. Installing it...
Output folder: E:\Users\zb\AppData\Local\Temp
Extract: get-pip.py... 100%
Execute: "C:\Python27\python" "E:\Users\zb\AppData\Local\Temp\get-pip.py"
Delete file: E:\Users\zb\AppData\Local\Temp\get-pip.py
Wheel not detected in your system. Installing it...
Wheel not installed. Error code was: error!

**Comment by MefhigosetH** [comment]
I think this error is resolved now.
