### ISSUE TITLE
can't compile code using command line on Raspberry Pi 2

### ISSUE THREAD

**Issue by jimgregory** [PinguinoIDE/pinguino-ide#50]
I am unable to compile using the command line.  When I attempt to compile I get an error:

> /usr/share/pinguino-11:$ python pinguino.py -f ~/program.pde -l v4 -p25k50
> Traceback (most recent call last):
>  File "pinguino.py", line 118, in <module>
>    os.environ["PINGUINO_DEBUGMODE"] = str(parser.devmode)
> AttributeError: 'Namespace' object has no attribute 'devmode'

If I comment out line 118 and attempt to recompile again, I get another error:

> /usr/share/pinguino-11:$ python pinguino.py -f ~/program.pde -l v4 -p25k50
> using Pinguino 25k50 board
> using boot4 bootloader
> Traceback (most recent call last):
>  File "pinguino.py", line 260, in <module>
>    pinguino.compile_file(filename)
>  File "/usr/share/pinguino-11/qtgui/pinguino_api/pinguino.py", line 31, in compile_file
>    self.**compiled** = data["verified"]
> TypeError: 'NoneType' object has no attribute '**getitem**'

I am using version 11.20150609 of the IDE on a Raspberry Pi 2.  

Compilation using the graphical IDE works great, BTW.  I just can't compile from the command line.

**Comment by YeisonEng** [comment]
Hi @jimgregory 
let me update pinguino-ide-tk, and check what happened.

**Comment by YeisonEng** [comment]
Hi @jimgregory try with the last git versión.

**Comment by MefhigosetH** [comment]
No user feedback.
