### ISSUE TITLE
Only compiles from "example" directory

### ISSUE THREAD

**Issue by jwzumwalt** [PinguinoIDE/pinguino-ide#55]
System: Win7 x64
## **\*  Update  2015.12.14 ***

I had copied all the examples into a separate directory to play around. I did not want to ruin the originals, I have since found out that if a program name is the same as an existing file or dir name, it will not compile. In other words... two duplicate file or directory names (even if in different sub-folders) will jam the compile. It seems the Java Engine or IDE is keeping track of names and does not tolerate identical ones. 

I also noticed that UECIDE which is also a spin off of MPIDE has this same problem. The original parent code appears to have had the problem and has been inherited by all the spin-offs.

---

Will only compile programs from the [user|example] directory. If you move or rename this directory, programs will not compile.
ERROR:
[OUT] ERROR: p32-gcc.exe: error: led\Blink: No such file or directory

REPRODUCED:
If I open an "example" then re-save it in a different directory, future attempts to compile it will fail. It seems the IDE is keeping track of program names and will not tolerate duplicate names - even if they are in different directories.

**Comment by jwzumwalt** [comment]
After looking further, it appears that gcc may have a hard link???
[OUT] ERROR: p32-gcc.exe: error: led\Blink: No such file or directory

**Comment by jwzumwalt** [comment]
This seems to be related to this problem...
If a program name is the same as an existing file or dir name, it will not compile.

**Comment by MefhigosetH** [comment]
v11 not supported now.
