### ISSUE TITLE
Need default "program" directory setting

### ISSUE THREAD

**Issue by jwzumwalt** [PinguinoIDE/pinguino-ide#56]
A user editable default directory settings is needed where the ide will look for programs.
For example  "C:\Users<user_name>\Documents\pinguino"
or
"C:\version11\myprojects"

**Comment by YeisonEng** [comment]
Hi @jwzumwalt 
I have added a new directory in `C:\pinguino-11\user\local` (or `~/.pinguino/local` for other systems) with this purpose.
https://github.com/PinguinoIDE/pinguino-ide/commit/c93bd5676ff6b75e2607286ffbe5a081e5745439

Hasta pronto.

**Comment by jwzumwalt** [comment]
Thanks for looking into this.

This should not be a hard coded directory. It should be user editable. For example, I prefer all my code in the "docs" directory so that a crash or os re-install does not loose the code in a forgotten program directory. This should be a setting under "preferences".

**Comment by MefhigosetH** [comment]
I think this feature is already implemented now.
