### ISSUE TITLE
Need to use default system folder view

### ISSUE THREAD

**Issue by jwzumwalt** [PinguinoIDE/pinguino-ide#57]
The IDE forces a folder icon view of file listings. The system default view should be used instead.

For example, I have about 60 folders in the default directory and seeing icons is useless. My default view is an alphabetized "details" with a font size that makes finding files and folders much easier than screens of icons.

**Comment by YeisonEng** [comment]
Hi, can you post a image to get the idea?, I have no access to Windows in
this moment.

On Mon, Dec 14, 2015, 3:01 AM jwzumwalt <notifications@github.com> wrote:

> The IDE forces a folder icon view of file listings The system default view
> should be used instead For example, I have about 60 folders in the default
> directory and seeing icons is useless My default view is an alphabetized
> "details" with a font size that makes finding files and folders much easier
> than screens of icons
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PinguinoIDE/pinguino-ide/issues/57>.
>
-- 

Yeison Nolberto Cardona Álvarez
@yeisoneng
Manizales Caldas (Colombia)
Estudiante de Ingeniería Electrónica
Universidad Nacional de Colombia

**Comment by jwzumwalt** [comment]
Thanks for looking at this problem.
FYI - The file dialog box folder view is set by the application developer, one of the dialog box properties.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms646960%28v=vs.85%29.aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms645524%28v=vs.85%29.aspx

![folder_view](https://cloud.githubusercontent.com/assets/5616209/11801800/8675039e-a2a6-11e5-8a38-412ace0c1f46.png)

**Comment by YeisonEng** [comment]
Hi @jwzumwalt 
This feature is hadled by PySide, there is currently no way to set the `ViewMode` for a native-dialog.

Hasta pronto.

**Comment by jwzumwalt** [comment]
Thank you for looking into this. 

I suspected something like this was the problem. I am not a JAVA or PY programmer but had expected JAVA to be the problem :( (In C or C++ there is a System Environment variable that the App can read to use the default view.
