### ISSUE TITLE
 Graphical programming error on save file on windows 10 (64bits)

### ISSUE THREAD

**Issue by lcgamboa** [PinguinoIDE/pinguino-ide#67]
Hi,

I´m using pinguino stable 11.0-beta.4 on windows 10 64bits.

When I programming with graphical blocks I don´t have any problem. But if I save the file .gpde and reopen it, the blocks are all disconnected and IDE sometimes freeze. It´s impossible to rearrange the blocks. I have tested this in two computers.
I have the same behaviour using developement version 12 in windows 10!
Using version 11 on Linux I don´t have any problems.  

Open the blink.gpde example and save it renamed to blink_saved.gpde result apparently in one file with problem. 
I found the error in code, but I don't know how to solve.
The error is in the line 352 of file qtgui/gide/app/graphical.py in the re.findall() function. In the Linux the function returns the correct widget id, in the windows not.
Look the pictures in annex.
This problems affects pinguino (v11 and v12) using the python2.7(32 or 64 bits) or python3.4 (32 or 64 bits) in the windows 10 (64 bits).

![pinguino_windows_error](https://cloud.githubusercontent.com/assets/13749258/17457180/ab62d5ee-5bc6-11e6-846b-b1412e6a8aef.png)
![pinguino_linux_ok](https://cloud.githubusercontent.com/assets/13749258/17457181/ab85a48e-5bc6-11e6-8ce3-4d072816c71b.png)

**Comment by lcgamboa** [comment]
Studying how regular expressions work in python I managed to solve the problem.
The problem is the capital letters in windows 10 64 bits expression.

replace the line 352 of file qtgui/gide/app/graphical.py 
`                id_ = re.findall("[.]*0x[\dabcdef]*[.]*", widget.__str__())[0]`
to
`                id_ = re.findall("[.]*0x[\dabcdefABCDEF]*[.]*", widget.__str__())[0]`
solve the error.

**Comment by YeisonEng** [comment]
Hi @lcgamboa 
Fixed in the last commit https://github.com/PinguinoIDE/pinguino-ide/commit/8cad6186ba7fe9e3480492944929c8367343009a, for v12 branch.
Thanks.
