### ISSUE TITLE
Automatic bug-reports

### ISSUE THREAD

**Issue by rblanchot** [PinguinoIDE/pinguino-ide#68]
Automatic bug-reports that version 12 sends, seem to go nowhere, at least they are not reported at https://github.com/PinguinoIDE/pinguino-ide/issues or at https://github.com/PinguinoIDE/pinguino-libraries/issues

**Comment by YeisonCardona** [comment]
I change this feature, now users can upload directly to GitHub with their username and password.
6d297b832a5c0cd86e7ad2116590d2acecdcad71
![screenshot_20170220_230910](https://cloud.githubusercontent.com/assets/4206584/23150515/f95f35fc-f7c1-11e6-8946-7003f51d8263.png)

**Comment by YeisonCardona** [comment]
So `requests` is now a dependence for v12.

**Comment by rblanchot** [comment]
I added requests as a dependency.
Thank you.
