### ISSUE TITLE
uploader not working

### ISSUE THREAD

**Issue by fcwpinguino** [PinguinoIDE/pinguino-ide#78]
Traceback (most recent call last):
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/pinguino.py", line 137, in upload
    data = self.__upload__()
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/pinguino_tools.py", line 297, in __upload__
    result = self.upload_hex()
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/uploader/uploader.py", line 233, in upload_hex
    self.uploader.uploadDevice(self.hex_file, self.board)
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/uploader/uploader8.py", line 602, in uploadDevice
    device = self.getDevice(board)
  File "/opt/pinguino/v12/pinguino/qtgui/pinguino_core/uploader/uploader.py", line 115, in getDevice
    device = usb.core.find(idVendor=board.vendor, idProduct=board.product)
AttributeError: 'module' object has no attribute 'core'

os.uname: ('Linux', 'debian', '3.16.0-4-amd64', '#1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04)', 'x86_64')
os.name: posix
os.environ: {'LD_LIBRARY_PATH': '/usr/lib32:/usr/lib:/usr/lib64', 'GLADE_PIXMAP_PATH': ':', 'PINGUINO_USER_PATH': '/home/fred/Pinguino/12', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm/data/fred', 'PINGUINO_DEFAULT_FILES': '/home/fred/Pinguino/12/local', 'PINGUINO_NAME': 'Pinguino IDE', 'XDG_CURRENT_DESKTOP': 'XFCE', 'PINGUINO_BOARD_ARCH': '8', 'LOGNAME': 'fred', 'XDG_SEAT': 'seat0', 'HOME': '/home/fred', 'XDG_VTNR': '7', 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games', 'DISPLAY': ':0.0', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LANG': 'en_US.utf8', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XAUTHORITY': '/home/fred/.Xauthority', 'PINGUINO_OS_NAME': 'linux', 'SESSION_MANAGER': 'local/debian:@/tmp/.ICE-unix/933,unix/debian:/tmp/.ICE-unix/933', 'XDG_DATA_DIRS': '/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share', 'PINGUINO_OS_ARCH': '64bit', 'PINGUINO_PROJECT': '', 'PINGUINO_PYTHON': '2', 'GLADE_CATALOG_PATH': ':', 'PINGUINO_VERSION': '12.0.39-beta.2', 'SSH_AGENT_PID': '919', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.39-beta.2', 'GLADE_MODULE_PATH': ':', 'PINGUINO_LIB': '/opt/pinguino/v12/pinguino', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'GDMSESSION': 'lightdm-xsession', 'PINGUINO_MODE': 'NORMAL', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'XDG_SESSION_ID': '1', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-4QcSUcsl49,guid=b5655e74f51ca569e08d1cbf58c1cc1f', 'DESKTOP_SESSION': 'lightdm-xsession', 'GPG_AGENT_INFO': '/run/user/1000/keyring/gpg:0:1', 'XDG_CONFIG_DIRS': '/etc/xdg', 'PINGUINO_INSTALL_PATH': '/opt/pinguino/v12', 'PINGUINO_USERLIBS_PATH': '/opt/pinguino/v12/pinguinolibs', 'PWD': '/home/fred', 'XDG_MENU_PREFIX': 'xfce-', 'PINGUINO_CAN_COMPILE': 'True', 'USER': 'fred'}

**Comment by MefhigosetH** [comment]
Duplicate #84
