### ISSUE TITLE
Problem uploading V11

### ISSUE THREAD

**Issue by bashman** [PinguinoIDE/pinguino-ide#79]
Ubuntu 16, 32 bits. pinguino ide 11, installed from script. 
Board 2550

[DEBUG] Starting '__upload__' from 'qtgui.pinguino_api.pinguino_tools'
[DEBUG] Starting 'upload' from 'qtgui.pinguino_api.uploader.uploader'
[DEBUG] Looking for a Pinguino device ...
[DEBUG] Found device 0x1D6B:0x0002
[DEBUG] Found device 0x090C:0x3714
[DEBUG] Found device 0x1D6B:0x0002
[DEBUG] Found device 0x1D6B:0x0001
[DEBUG] Found device 0x1D6B:0x0001
[DEBUG] Found device 0x1D6B:0x0001
[DEBUG] Found device 0x0458:0x003A
[DEBUG] Found device 0x04D8:0xFEAA
[DEBUG] Pinguino found
[DEBUG] OS is linux
[DEBUG] Traceback (most recent call last):
[DEBUG]   File '/opt/pinguino/v11/qtgui/pinguino_api/tools.py', line 23, in inset
[DEBUG]     ret = f(*args, **kwaargs)
[DEBUG]   File '/opt/pinguino/v11/qtgui/pinguino_api/uploader/uploader.py', line 179, in upload
[DEBUG]     self.uploader.uploadDevice(self.hexfile, self.board)
[DEBUG]   File '/opt/pinguino/v11/qtgui/pinguino_api/uploader/uploaderVSC.py', line 265, in uploadDevice
[DEBUG]     handle = self.initDevice(device)
[DEBUG]   File '/opt/pinguino/v11/qtgui/pinguino_api/uploader/uploader.py', line 117, in initDevice
[DEBUG]     handle.setConfiguration(self.ACTIVE_CONFIG)
[DEBUG]   File '/usr/lib/python2.7/dist-packages/usb/legacy.py', line 253, in setConfiguration
[DEBUG]     self.dev.set_configuration(configuration)
[DEBUG]   File '/usr/lib/python2.7/dist-packages/usb/core.py', line 799, in set_configuration
[DEBUG]     self._ctx.managed_set_configuration(self, configuration)
[DEBUG]   File '/usr/lib/python2.7/dist-packages/usb/core.py', line 127, in managed_set_configuration
[DEBUG]     self.managed_open()
[DEBUG]   File '/usr/lib/python2.7/dist-packages/usb/core.py', line 105, in managed_open
[DEBUG]     self.handle = self.backend.open_device(self.dev)
[DEBUG]   File '/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py', line 722, in open_device
[DEBUG]     return _DeviceHandle(dev)
[DEBUG]   File '/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py', line 600, in __init__
[DEBUG]     _check(_lib.libusb_open(self.devid, byref(self.handle)))
[DEBUG]   File '/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py', line 552, in _check
[DEBUG]     raise USBError(_strerror(ret), ret, _libusb_errno[ret])
[DEBUG] USBError: [Errno 5] Input/Output Error
[DEBUG] 
[DEBUG] Time spent for '__upload__': 0.97 s
[DEBUG] Ending '__upload__'

**Comment by MefhigosetH** [comment]
v11 not supported now.
