### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by UserYao** [PinguinoIDE/pinguino-ide#85]
Traceback (most recent call last):
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 161, in wrapped
    if saved: fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 174, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\core.py", line 786, in pinguino_compile
    compile_code()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\core.py", line 765, in <lambda>
    compile_code = lambda :self.pinguinoAPI.compile_file([filename])
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino.py", line 85, in compile_file
    data = self.verify(file_path)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 225, in verify
    self.set_os_variables()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 126, in set_os_variables
    self.COMPILER_8BIT = self.glob_path(self.COMPILER_8BIT)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 136, in glob_path
    return dirs[-1]
IndexError: list index out of range

os.name: nt
os.environ: {'TMP': 'C:\\Users\\JIAQIA~1\\AppData\\Local\\Temp', 'COMPUTERNAME': 'WINDOWS10-F65SA', 'PINGUINO_USER_PATH': 'C:\\Users\\Jiaqiang Yao\\Documents\\Pinguino\\v12', 'USERDOMAIN': 'WINDOWS10-F65SA', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PINGUINO_NAME': 'Pinguino IDE', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '3a09', 'SYSTEMROOT': 'C:\\WINDOWS', 'PATH': 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\MATLAB\\R2016b\\runtime\\win64;C:\\Program Files\\MATLAB\\R2016b\\bin;C:\\Program Files\\MATLAB\\R2013a\\runtime\\win64;C:\\Program Files\\MATLAB\\R2013a\\bin;C:\\Users\\Jiaqiang Yao\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files\\Pinguino\\p8\\bin', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'TEMP': 'C:\\Users\\JIAQIA~1\\AppData\\Local\\Temp', 'PINGUINO_OS_NAME': 'windows', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PINGUINO_LIB': 'C:\\Program Files\\Pinguino\\v12\\pinguino', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PINGUINO_OS_ARCH': '64bit', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'PINGUINO_PYTHON': '2', 'LOCALAPPDATA': 'C:\\Users\\Jiaqiang Yao\\AppData\\Local', 'HOMEPATH': '\\Users\\Jiaqiang Yao', 'USERDOMAIN_ROAMINGPROFILE': 'WINDOWS10-F65SA', 'PINGUINO_VERSION': '12.0.39-beta.2', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'Jiaqiang Yao', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.39-beta.2', 'LOGONSERVER': '\\\\WINDOWS10-F65SA', 'PROMPT': '$P$G', 'SESSIONNAME': 'Console', 'PROGRAMDATA': 'C:\\ProgramData', 'ONEDRIVE': 'C:\\Users\\Jiaqiang Yao\\OneDrive', 'PINGUINO_MODE': 'NORMAL', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PINGUINO_DEFAULT_FILES': 'C:\\Users\\Jiaqiang Yao\\Documents\\Pinguino\\v12\\local', 'WINDIR': 'C:\\WINDOWS', 'APPDATA': 'C:\\Users\\Jiaqiang Yao\\AppData\\Roaming', 'HOMEDRIVE': 'C:', 'PINGUINO_USERLIBS_PATH': 'C:\\Users\\Jiaqiang Yao\\Documents\\Pinguino\\v12\\pinguinolibs', 'SYSTEMDRIVE': 'C:', 'PINGUINO_INSTALL_PATH': 'C:\\Program Files\\Pinguino\\v12\\', 'NUMBER_OF_PROCESSORS': '4', 'PINGUINO_PROJECT': '', 'PINGUINO_BOARD_ARCH': '32', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'PINGUINO_CAN_COMPILE': 'True', 'USERPROFILE': 'C:\\Users\\Jiaqiang Yao'}

**Comment by MefhigosetH** [comment]
Duplicate #101
