### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yondergb** [PinguinoIDE/pinguino-ide#90]
Traceback (most recent call last):
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino.py", line 137, in upload
    data = self.__upload__()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 297, in __upload__
    result = self.upload_hex()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader.py", line 233, in upload_hex
    self.uploader.uploadDevice(self.hex_file, self.board)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 604, in uploadDevice
    device = self.getDevice(board)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\uploader\uploader.py", line 115, in getDevice
    device = usb.core.find(idVendor=board.vendor, idProduct=board.product)
  File "C:\Python27\lib\site-packages\usb\core.py", line 1263, in find
    raise NoBackendError('No backend available')
NoBackendError: No backend available

os.name: nt
os.environ: {'TMP': 'C:\\Users\\yender\\AppData\\Local\\Temp', 'COMPUTERNAME': 'YENDER-PC', 'PINGUINO_USER_PATH': 'C:\\Users\\yender\\Documents\\Pinguino\\v12', 'USERDOMAIN': 'yender-PC', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'PINGUINO_NAME': 'Pinguino IDE', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'x86 Family 6 Model 15 Stepping 13, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '0f0d', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Microchip\\xc8\\v1.42\\bin;C:\\Program Files\\Pinguino\\p8\\bin', 'WINDOWS_TRACING_FLAGS': '3', 'TEMP': 'C:\\Users\\yender\\AppData\\Local\\Temp', 'PINGUINO_OS_NAME': 'windows', 'PINGUINO_LIB': 'C:\\Program Files\\Pinguino\\v12\\pinguino', 'PROCESSOR_ARCHITECTURE': 'x86', 'PINGUINO_OS_ARCH': '32bit', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'PINGUINO_PYTHON': '2', 'SESSIONNAME': 'Console', 'HOMEPATH': '\\Users\\yender', 'PINGUINO_VERSION': '12.0.39-beta.2', 'USERNAME': 'yender', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.39-beta.2', 'LOGONSERVER': '\\\\YENDER-PC', 'PROMPT': '$P$G', 'LOCALAPPDATA': 'C:\\Users\\yender\\AppData\\Local', 'PROGRAMDATA': 'C:\\ProgramData', 'PINGUINO_INSTALL_PATH': 'C:\\Program Files\\Pinguino\\v12\\', 'PINGUINO_MODE': 'NORMAL', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PINGUINO_PROJECT': '', 'PINGUINO_DEFAULT_FILES': 'C:\\Users\\yender\\Documents\\Pinguino\\v12\\local', 'JD2_HOME': 'C:\\Users\\yender\\AppData\\Local\\JDownloader 2.0', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 'WINDOWS_TRACING_LOGFILE': 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log', 'HOMEDRIVE': 'C:', 'PINGUINO_USERLIBS_PATH': 'C:\\Users\\yender\\Documents\\Pinguino\\v12\\pinguinolibs', 'SYSTEMDRIVE': 'C:', 'PINGUINO_BOARD_ARCH': '8', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'NUMBER_OF_PROCESSORS': '2', 'APPDATA': 'C:\\Users\\yender\\AppData\\Roaming', 'PROCESSOR_LEVEL': '6', 'MCC_INCLUDE': 'C:\\Program Files\\Microchip\\xc8\\v1.42/h', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'PINGUINO_CAN_COMPILE': 'True', 'USERPROFILE': 'C:\\Users\\yender'}

**Comment by MefhigosetH** [comment]
Duplicate #98
