### ISSUE TITLE
NoBackendError: No backend available

### ISSUE THREAD

**Issue by jherssonml** [PinguinoIDE/pinguino-ide#94]
Traceback (most recent call last):
  File "C:\Program Files\Pinguinov12\v12\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguinov12\v12\pinguino\qtgui\ide\methods\decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguinov12\v12\pinguino\qtgui\ide\methods\core.py", line 863, in pinguino_upload
    uploaded, result = self.pinguinoAPI.upload()
  File "C:\Program Files\Pinguinov12\v12\pinguino\qtgui\pinguino_core\pinguino.py", line 137, in upload
    data = self.__upload__()
  File "C:\Program Files\Pinguinov12\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 297, in __upload__
    result = self.upload_hex()
  File "C:\Program Files\Pinguinov12\v12\pinguino\qtgui\pinguino_core\uploader\uploader.py", line 233, in upload_hex
    self.uploader.uploadDevice(self.hex_file, self.board)
  File "C:\Program Files\Pinguinov12\v12\pinguino\qtgui\pinguino_core\uploader\uploader8.py", line 604, in uploadDevice
    device = self.getDevice(board)
  File "C:\Program Files\Pinguinov12\v12\pinguino\qtgui\pinguino_core\uploader\uploader.py", line 115, in getDevice
    device = usb.core.find(idVendor=board.vendor, idProduct=board.product)
  File "C:\Python27\lib\site-packages\usb\core.py", line 1263, in find
    raise NoBackendError('No backend available')
NoBackendError: No backend available

os.name: nt
os.environ: {'TMP': 'C:\\Users\\JH\\AppData\\Local\\Temp', 'COMPUTERNAME': 'MYPCJHERSSON', 'PINGUINO_USER_PATH': 'C:\\Users\\JH\\Documents\\Pinguino\\v12', 'USERDOMAIN': 'MYPCJHERSSON', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PINGUINO_NAME': 'Pinguino IDE', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PINGUINO_LIB': 'C:\\Program Files\\Pinguinov12\\v12\\pinguino', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 78 Stepping 3, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '4e03', 'PATH': 'C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Files\\cpp\\bin\\Intel64;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Oberthur Technologies\\AuthentIC Webpack\\Dlls;C:\\Program Files (x86)\\Oberthur Technologies\\AuthentIC Webpack\\Dlls;C:\\Program Files (x86)\\Microchip\\xc8\\v1.34\\bin;C:\\Program Files (x86)\\Microchip\\xc8\\v1.44\\bin;C:\\Program Files\\nodejs\\;C:\\altera\\15.0\\modelsim_ase\\win32aloem;C:\\Users\\JH\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\JH\\AppData\\Local\\atom\\bin;C:\\Users\\JH\\AppData\\Roaming\\npm;C:\\Program Files\\Pinguinov12\\p8\\bin', 'SYSTEMROOT': 'C:\\WINDOWS', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'C_EM64T_REDIST11': 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Files\\cpp\\', 'QUARTUS_ROOTDIR': 'C:\\altera\\15.0\\quartus', 'TEMP': 'C:\\Users\\JH\\AppData\\Local\\Temp', 'PINGUINO_OS_NAME': 'windows', 'ILLDIR': 'C:\\Program Files (x86)\\Common Files\\Autodesk Shared\\Materials\\', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'ALTERAOCLSDKROOT': 'C:\\altera\\15.0\\hld', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PINGUINO_OS_ARCH': '64bit', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'PINGUINO_PYTHON': '2', 'LOCALAPPDATA': 'C:\\Users\\JH\\AppData\\Local', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'HOMEPATH': '\\Users\\JH', 'USERDOMAIN_ROAMINGPROFILE': 'MYPCJHERSSON', 'PINGUINO_VERSION': '12.0.39-beta.2', 'CM2015DIR': 'C:\\Program Files (x86)\\Common Files\\Autodesk Shared\\Materials\\', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'jhersson.jul', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.39-beta.2', 'SOPC_KIT_NIOS2': 'C:\\altera\\15.0\\nios2eds', 'LOGONSERVER': '\\\\MYPCJHERSSON', 'PROMPT': '$P$G', 'SESSIONNAME': 'Console', 'PROGRAMDATA': 'C:\\ProgramData', 'ONEDRIVE': 'C:\\Users\\JH\\OneDrive', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'PINGUINO_MODE': 'NORMAL', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PINGUINO_DEFAULT_FILES': 'C:\\Users\\JH\\Documents\\Pinguino\\v12\\local', 'WINDIR': 'C:\\WINDOWS', 'APPDATA': 'C:\\Users\\JH\\AppData\\Roaming', 'HOMEDRIVE': 'C:', 'OMP_NUM_THREADS': '4', 'PINGUINO_USERLIBS_PATH': 'C:\\Users\\JH\\Documents\\Pinguino\\v12\\pinguinolibs', 'SYSTEMDRIVE': 'C:', 'PINGUINO_INSTALL_PATH': 'C:\\Program Files\\Pinguinov12\\v12\\', 'NUMBER_OF_PROCESSORS': '4', 'QSYS_ROOTDIR': 'C:\\altera\\15.0\\quartus\\sopc_builder\\bin', 'PINGUINO_PROJECT': '', 'PINGUINO_BOARD_ARCH': '8', 'PROCESSOR_LEVEL': '6', 'MCC_INCLUDE': 'C:\\Program Files (x86)\\Microchip\\xc8\\v1.44/h', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'PINGUINO_CAN_COMPILE': 'True', 'USERPROFILE': 'C:\\Users\\JH'}

**Comment by MefhigosetH** [comment]
Duplicate #98
