### ISSUE TITLE
Fedora 27 x64 Install from this thread http://forum.pinguino.cc/showthread.php?tid=4820, the script installer from github is only for debian thks

### ISSUE THREAD

**Issue by maigke** [PinguinoIDE/pinguino-ide#96]
Traceback (most recent call last):
  File "/opt/pinguino/v12/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/opt/pinguino/v12/pinguino/qtgui/ide/ide.py", line 132, in __init__
    self.PinguinoAutoCompleter = PinguinoAutoCompleter()
  File "/opt/pinguino/v12/pinguino/qtgui/ide/custom_widgets/code_editor/autocompleter.py", line 59, in __init__
    with open(os.path.join(os.getenv("PINGUINO_USER_PATH"), "reserved.pickle"), "rb") as file_reserved:
IOError: [Errno 2] No such file or directory: '/home/miguel/.pinguino/v12/reserved.pickle'

os.uname: ('Linux', 'NastyBox', '4.15.12-301.fc27.x86_64', '#1 SMP Thu Mar 22 19:25:27 UTC 2018', 'x86_64')
os.name: posix
os.environ: {'XDG_SESSION_TYPE': 'x11', '_JAVA_OPTIONS': '-Dawt.useSystemAAFontSettings=lcd', 'SHELL': '/bin/bash', 'XDG_DATA_DIRS': '/home/miguel/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/', 'HISTSIZE': '1000', 'VH_MAXERR': '10', 'XPAT_PARAM_NAME': '/etc/alliance/xpat.par', 'XMODIFIERS': '@im=ibus', 'XSCH_PARAM_NAME': '/etc/alliance/xsch.par', 'PINGUINO_VERSION': '12.0.41-beta.2', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.41-beta.2', 'XDG_RUNTIME_DIR': '/run/user/1000', 'PINGUINO_MODE': 'NORMAL', 'XDG_SESSION_ID': '6', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'DESKTOP_SESSION': 'gnome-xorg', 'HOSTNAME': 'NastyBox', 'MBK_VSS': 'vss', 'XFSM_PARAM_NAME': '/etc/alliance/xfsm.par', 'MAIL': '/var/spool/mail/miguel', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:', 'MBK_OUT_PH': 'ap', 'DREAL_TECHNO_NAME': '/etc/alliance/cmos.dreal', 'MBK_CATA_LIB': '.:/usr/share/alliance/cells/sxlib:/usr/share/alliance/cells/dp_sxlib:/usr/share/alliance/cells/rflib:/usr/share/alliance/cells/rf2lib:/usr/share/alliance/cells/ramlib:/usr/share/alliance/cells/romlib:/usr/share/alliance/cells/pxlib', 'MBK_WORK_LIB': '.', 'BASH_FUNC_module%%': '() {  eval `/usr/bin/modulecmd bash $*`\n}', 'MBK_SPI_MODEL': '/etc/alliance/spimodel.cfg', 'XDG_CURRENT_DESKTOP': 'GNOME', 'PINGUINO_BOARD_ARCH': '8', 'CVS_RSH': 'ssh', 'USER': 'miguel', 'QTDIR': '/usr/lib64/qt-3.3', 'XDG_VTNR': '2', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'JOURNAL_STREAM': '9:1915055', 'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/29188,unix/unix:/tmp/.ICE-unix/29188', 'SHLVL': '2', 'PINGUINO_OS_ARCH': '64bit', 'WINDOWID': '31457286', 'MODULESHOME': '/usr/share/Modules', 'XDG_SESSION_DESKTOP': 'gnome-xorg', 'GDMSESSION': 'gnome-xorg', 'XDG_MENU_PREFIX': 'gnome-', '_': './pinguino-ide.py', 'MODULEPATH': '/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles', 'PINGUINO_USERLIBS_PATH': '/opt/pinguino/v12/pinguinolibs', 'COLORTERM': 'truecolor', 'MBK_VDD': 'vdd', 'PINGUINO_USER_PATH': '/home/miguel/.pinguino/v12', 'BASH_FUNC_scl%%': '() {  if [ "$1" = "load" -o "$1" = "unload" ]; then\n eval "module $@";\n else\n /usr/bin/scl "$@";\n fi\n}', 'GJS_DEBUG_OUTPUT': 'stderr', 'PINGUINO_NAME': 'Pinguino IDE', 'ALLIANCE_TOP': '/usr/lib64/alliance', 'HOME': '/home/miguel', 'MBK_IN_LO': 'vst', 'DISPLAY': ':0', 'LANG': 'es_MX.UTF-8', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'RDS_IN': 'cif', 'MBK_SCALE_X': '100', 'QTINC': '/usr/lib64/qt-3.3/include', 'VH_DLYSFX': 'dly', 'MBK_CATAL_NAME': 'CATAL', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'USERNAME': 'miguel', 'PINGUINO_LIBS_PATH': '/opt/pinguino/v12', 'PINGUINO_LIB': '/opt/pinguino/v12/pinguino', 'VTE_VERSION': '5002', 'PINGUINO_PYTHON': '2', 'GENVIEW_TECHNO_NAME': '/etc/alliance/cmos.genview', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'MBK_OUT_LO': 'vst', 'KDEDIRS': '/usr', 'PINGUINO_DEFAULT_FILES': '/home/miguel/.pinguino/v12/local', 'GRAAL_TECHNO_NAME': '/etc/alliance/cmos.graal', 'PINGUINO_CAN_COMPILE': 'True', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'miguel', 'XDG_SEAT': 'seat0', 'TPD_GLOBAL': '/usr/share/toped/', 'PATH': '/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/libexec/sdcc:/home/miguel/.local/bin:/home/miguel/bin:/usr/libexec/sdcc', 'PINGUINO_32_LIBS_PATH': '/opt/pinguino/v12/p32', 'VH_BEHSFX': 'vbe', 'PINGUINO_OS_NAME': 'linux', 'TPD_LOCAL': '/home/miguel', 'RDS_OUT': 'cif', 'PINGUINO_PROJECT': '', 'WINDOWPATH': '2', 'MBK_C4_LIB': './cellsC4', 'RDS_TECHNO_NAME': '/etc/alliance/cmos.rds', 'VH_PATSFX': 'pat', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'TERM': 'xterm-256color', 'MBK_TARGET_LIB': '/usr/share/alliance/cells/sxlib', 'ELP_TECHNO_NAME': '/etc/alliance/prol.elp', 'PINGUINO_8_LIBS_PATH': '/opt/pinguino/v12/p8', 'PINGUINO_INSTALL_PATH': '/opt/pinguino/v12', 'OLDPWD': '/opt/pinguino/v12/pinguino', 'LOADEDMODULES': '', 'GDM_LANG': 'es_MX.UTF-8', 'HISTCONTROL': 'ignoredups', 'PWD': '/opt/pinguino/v12', 'MBK_IN_PH': 'ap', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG'}

**Comment by MefhigosetH** [comment]
Duplicate #118
