### ISSUE TITLE
pic

### ISSUE THREAD

**Issue by mariomorenot** [PinguinoIDE/pinguino-ide#99]
Traceback (most recent call last):
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 25, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 161, in wrapped
    if saved: fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\decorators.py", line 174, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\core.py", line 786, in pinguino_compile
    compile_code()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\ide\methods\core.py", line 765, in <lambda>
    compile_code = lambda :self.pinguinoAPI.compile_file([filename])
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino.py", line 85, in compile_file
    data = self.verify(file_path)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 225, in verify
    self.set_os_variables()
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 126, in set_os_variables
    self.COMPILER_8BIT = self.glob_path(self.COMPILER_8BIT)
  File "C:\Program Files\Pinguino\v12\pinguino\qtgui\pinguino_core\pinguino_tools.py", line 136, in glob_path
    return dirs[-1]
IndexError: list index out of range

os.name: nt
os.environ: {'TMP': 'C:\\Users\\m_a_m\\AppData\\Local\\Temp', 'PT7HOME': 'C:\\Program Files\\Cisco Packet Tracer 7.1.1', 'COMPUTERNAME': 'DESKTOP-9CBIM90', 'PROCESSOR_LEVEL': '6', 'PINGUINO_USER_PATH': 'C:\\Users\\m_a_m\\OneDrive\\Documentos\\Pinguino\\v12', 'USERDOMAIN': 'DESKTOP-9CBIM90', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PSMODULEPATH': 'C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'PINGUINO_NAME': 'Pinguino IDE', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 78 Stepping 3, GenuineIntel', 'VBOX_MSI_INSTALL_PATH': 'C:\\Program Files\\Oracle\\VirtualBox\\', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '4e03', 'PATH': 'C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;c:\\Program Files\\Intel\\IntelSGXPSW\\bin\\x64\\Release\\;c:\\Program Files\\Intel\\IntelSGXPSW\\bin\\win32\\Release\\;C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\;c:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\;c:\\Program Files\\Microsoft SQL Server\\100\\Tools\\Binn\\;c:\\Program Files\\Microsoft SQL Server\\100\\DTS\\Binn\\;c:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\VSShell\\Common7\\IDE\\;c:\\Program Files (x86)\\Microsoft SQL Server\\100\\DTS\\Binn\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin\\;C:\\Program Files\\IVI Foundation\\VISA\\Win64\\Bin\\;C:\\Program Files (x86)\\IVI Foundation\\VISA\\WinNT\\Bin;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\x\\php;C:\\composer;C:\\Program Files\\MATLAB\\R2017a\\runtime\\win64;C:\\Program Files\\MATLAB\\R2017a\\bin;C:\\Users\\m_a_m\\AppData\\Local\\Programs\\Python\\Python37\\Scripts\\;C:\\Users\\m_a_m\\AppData\\Local\\Programs\\Python\\Python37\\;C:\\Users\\m_a_m\\AppData\\Local\\Programs\\Python\\Launcher\\;C:\\Users\\m_a_m\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\m_a_m\\AppData\\Roaming\\Composer\\vendor\\bin;C:\\Program Files\\Pinguino\\p8\\bin', 'SYSTEMROOT': 'C:\\WINDOWS', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'KMP_DUPLICATE_LIB_OK': 'TRUE', 'TEMP': 'C:\\Users\\m_a_m\\AppData\\Local\\Temp', 'PINGUINO_OS_NAME': 'windows', 'MKL_SERIAL': 'YES', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PINGUINO_LIB': 'C:\\Program Files\\Pinguino\\v12\\pinguino', 'VXIPNPPATH': 'C:\\Program Files (x86)\\IVI Foundation\\VISA\\', 'PINGUINO_OS_ARCH': '64bit', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'PINGUINO_PYTHON': '2', 'LOCALAPPDATA': 'C:\\Users\\m_a_m\\AppData\\Local', 'HOMEPATH': '\\Users\\m_a_m', 'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-9CBIM90', 'PINGUINO_VERSION': '12.0.39-beta.2', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'm_a_m', 'PINGUINO_FULLNAME': 'Pinguino IDE 12.0.39-beta.2', 'LOGONSERVER': '\\\\DESKTOP-9CBIM90', 'QT_DEVICE_PIXEL_RATIO': 'auto', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'NIEXTCCOMPILERSUPP': 'C:\\Program Files (x86)\\National Instruments\\Shared\\ExternalCompilerSupport\\C\\', 'PROGRAMDATA': 'C:\\ProgramData', 'PT6HOME': 'C:\\Program Files (x86)\\Cisco Packet Tracer 6.3', 'ONEDRIVE': 'C:\\Users\\m_a_m\\OneDrive', 'PROMPT': '$P$G', 'PINGUINO_MODE': 'NORMAL', 'PUBLIC': 'C:\\Users\\Public', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'ASL.LOG': 'Destination=file', 'PINGUINO_DEFAULT_FILES': 'C:\\Users\\m_a_m\\OneDrive\\Documentos\\Pinguino\\v12\\local', 'WINDIR': 'C:\\WINDOWS', 'UOIPME_REG_PATH': 'C:\\Program Files\\Intel Corporation\\USB over IP', 'APPDATA': 'C:\\Users\\m_a_m\\AppData\\Roaming', 'HOMEDRIVE': 'C:', 'OMP_NUM_THREADS': '4', 'OS': 'Windows_NT', 'SYSTEMDRIVE': 'C:', 'PINGUINO_INSTALL_PATH': 'C:\\Program Files\\Pinguino\\v12\\', 'NUMBER_OF_PROCESSORS': '4', 'PINGUINO_PROJECT': '', 'PINGUINO_BOARD_ARCH': '8', 'VXIPNPPATH64': 'C:\\Program Files\\IVI Foundation\\VISA\\', 'PINGUINO_USERLIBS_PATH': 'C:\\Users\\m_a_m\\OneDrive\\Documentos\\Pinguino\\v12\\pinguinolibs', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', '__COMPAT_LAYER': 'Installer', 'ADSK_CLM_WPAD_PROXY_CHECK': 'FALSE', 'PINGUINO_CAN_COMPILE': 'True', 'USERPROFILE': 'C:\\Users\\m_a_m'}

**Comment by MefhigosetH** [comment]
Duplicate #101
